AssemblyScript/assemblyscript

- std/assembly.d.ts
- std/assembly/error.ts
- std/assembly/polyfills.ts
- std/portable.d.ts
- std/portable.js
- tests/compiler/std/polyfills.optimized.wat
- tests/compiler/std/polyfills.ts
- tests/compiler/std/polyfills.untouched.wat
I create another PR for [this](https://github.com/AssemblyScript/assemblyscript/pull/33)
> Add bswap/bswap16 post MVP polyfills

- snap/snapcraft.yaml
This package will let you publish the latest assemblyscript in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.
> Add the packaging metadata to build the assemblyscript snap

- NOTICE
- std/assembly.d.ts
- std/assembly/array.ts
- std/portable.d.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
Implemented `array.includes` method, improved spec compatibility for `array.indexOf`, added few missing tests.
`array.includes` was created as a new method, without using `indexOf` just because by spec they work slightly differently, especially for floats, so they can became different in the future.
> array.includes method

- std/assembly.d.ts
- std/assembly/builtins.ts
- std/portable.d.ts
- std/portable.js
- Add min & max values for decimals in portable defs.
Java:  https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#MIN_NORMAL
Swift: https://developer.apple.com/documentation/swift/double/1849547-leastnormalmagnitude
Rust:  https://rust-num.github.io/num/num_traits/float/trait.Float.html#tymethod.min_positive_value
and etc
> Add min normalized positive value for decimals

- std/assembly.d.ts
- std/assembly/array.ts
- std/portable.d.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
Added basic version of few other Array.prototype methods. They are not fully spec-compatible because we don't have method overloading.  After method overloading will be implemented, i'll return to this methods and will make arguments optional.
> add array methods: findIndex, reduce, some, every

- std/assembly/math.ts
- tests/compiler/std/libm.optimized.wat
- tests/compiler/std/libm.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.untouched.wat
+ new version produce less branchless machine code.
+ less comparision instructions
+ smaller wasm size (129 bytes vs 112 bytes)
> Improve Math#sign

- NOTICE
- src/compiler.ts
- tests/compiler/class-with-boolean-field.optimized.wat
- tests/compiler/class-with-boolean-field.ts
- tests/compiler/class-with-boolean-field.untouched.wat
Fixes #94
With `Type.bool`, size is 1, so dividing by 8 isn't the right way to convert to
byteSize. Instead, we need to use the `byteSize` property that does the proper
ceiling division.
I left out the allocation from the test so that the resulting wat files are
easier to read.
> Fix crash when assigning to bool class fields

- src/extra/ast.ts
- src/parser.ts
- tests/parser/trailing-commas.ts
- tests/parser/trailing-commas.ts.fixture.ts
Trailing commas are allowed in these situations in JS/TS:
* Array literals
* Argument lists
* Parameter lists
* Enums
* Type parameter lists
* Type argument lists (Technically filed as https://github.com/Microsoft/TypeScript/issues/21984 )
They're also allowed in these cases not (yet) supported by AssemblyScript:
* Object literals
* Array destructures
* Object destructures
All of these cases had similar-looking code, which needed to be tweaked to
handle the possibility of a comma before the close-delimiter. Type arguments
were a little different because they take a backtracking approach.
I also fixed a missing case in the AST printer: `export function` wasn't being
printed right.
> Implement optional trailing commas

- src/parser.ts
- src/tokenizer.ts
- tests/compiler/named-export-default.optimized.wat
- tests/compiler/named-export-default.ts
- tests/compiler/named-export-default.untouched.wat
- tests/compiler/named-import-default.optimized.wat
- tests/compiler/named-import-default.ts
- tests/compiler/named-import-default.untouched.wat
Progress toward #98
See the imports and exports grammar from the spec:
https://www.ecma-international.org/ecma-262/8.0/index.html#sec-imports
https://www.ecma-international.org/ecma-262/8.0/index.html#sec-exports
In particular, ImportSpecifier and ExportSpecifier use IdentifierName to
identify the import/export name rather than the more restrictive ImportedBinding
(or just Identifier). That means any keyword is allowed.
There are (at least) three contexts to think about in JS identifier parsing:
* In most contexts, identifiers like variable names can be any name except a
reserved word.
* Some keywords, like "as", are normally not keywords but have special
keyword-like meaning in specific situations. Acorn and Babel call these
"contextual keywords", and `tokenIsAlsoIdentifier` and …
> Allow keywords in named import/export syntax

- src/extra/ast.ts
- src/parser.ts
- tests/parser/trailing-commas.ts
- tests/parser/trailing-commas.ts.fixture.ts
This uses the same strategy as #97 for two more cases in the parser.
> Allow trailing commas in import and export statements

- src/builtins.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- tests/compiler.js
- tests/compiler/new-without-allocator.ts
This tripped me up, and it looks like others have run into it as well, so it
seems like a good idea to have a custom error message.
I also added a system for writing tests that assert that certain error codes are
triggered so that I could test this.
> Add a more helpful error message when you haven't defined an allocator

- .travis.yml
This ditches audits and `npm ci`, and caches `node_modules`. While there are certainly reasons not to do that, it speeds up builds significantly and appears to be less error prone in general.
>  Avoid some npm issues 

- std/assembly/internal/itoa.ts
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
No functional changes intended. Changes include possibly sharing locals at some occasions by pulling them into blocks with `let` and changing some types to `usize` where the value is used as an offset so it doesn't have to be wrapped each time in WASM64 if that ever becomes a thing.
@MaxGraey: Could you review this to make sure that there are no possibly actually expected integer overflows or something removed by making these changes? :)
> Minor itoa improvements

- cli/asc.js
Running with `--noLib` currently always fails. This is because the default global aliases that are always added aren't available with the --noLib flag, and a recently added check throws an exception. This change stops adding default global aliases if `--noLib` is specified, avoiding the error.
Example of error this fixed:
```
> @assemblyscript/i64@1.0.0 asbuild:untouched C:\src\assemblyscript\examples\i64-polyfill
> asc assembly/i64.ts -t build/untouched.wat -b build/untouched.wasm --validate --sourceMap --measure --noLib
ERROR: element not found: NativeMath
at t.initialize (C:\src\assemblyscript\dist\assemblyscript.js:1:66981)
at t.compile (C:\src\assemblyscript\dist\assemblyscript.js:1:175610)
at Object.t.compileProgram (C:\src\assemblyscript\dist\assemblyscript.js:1:357909)
at …
```
> Don't add default aliases if --noLib is set to avoid "element not found errors.

- std/assembly/math.ts
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.ts
- tests/compiler/std/math.untouched.wat
[Performance test](https://webassembly.studio/?f=5ucjmzcjpai).
On Firefox 62.0b14:
- fpow64: 606ms (Math.pow)
- ipow64: **54ms**
Related to #210
> Add integer power functions

- package.json
To allow using the loader as follow:
```javascript
const loader = require('assemblyscript/lib/loader');
```
> Add lib/loader/ to package.json

- std/assembly/dataview.ts
- std/assembly/index.d.ts
- std/portable/index.d.ts
- tests/compiler/std/dataview.ts
- tests/compiler/std/dataview.untouched.wat
Opening this for early feedback, as soon as I know I'm on the right track it should be very easy for me to add all the required methods.
Some questions:
1. Should I just `throw new RangeError('Out of bounds access')` when trying to access outside the bounds?
1. Is there any way to overload the `get*` functions for when `littleEndian` is known at compile time, or will the compiler just figure it out anyway?
e.g. something like this:
```ts
function getUint32(offset: number, littleEndian: false) { ... }
function getUint32(offset: number, littleEndian: true) { ... }
function getUint32(offset: number, littleEndian: boolean) { ... }
```
1. Do I have to register `DataView` as a global variable somewhere?
1. Where do I put the tests? I'm assuming somewhere under `tests/`, but then I'm a bit lost …
> Add DataView to standard library

- std/assembly/internal/typedarray.ts
- std/assembly/typedarray.ts
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.ts
- tests/compiler/std/typedarray.untouched.wat
This pull request implements the `TypedArray.prototype.map` method and cleans up the test suite, reducing  the number of lines in the `tests/compiler/std/typedarray.ts` file by 50%!
Any comments are enouraged.
Thanks for the heads up @dcodeIO.
> %TypedArray%.prototype.map and %TypedArray%.prototype.reduce/reduceRight test cleanup with Uint8ClampedArray changes

- std/assembly/array.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
The [AS code](https://webassembly.studio/?f=m2jl7gxp1m)
```
Print index: 0. value: 0
Print index: 1. value: 1
Print index: 2. value: 100
Print index: 3. value: 101
Print index: 4. value: 102
The array content:
Print index: 0. value: 0
Print index: 1. value: 1
Print index: 2. value: 333
Print index: 3. value: 334
Print index: 4. value: 335
Print index: 5. value: 336
Print index: 6. value: 337
Print index: 7. value: 338
Print index: 8. value: 339
Print index: 9. value: 340
```
The forEach visited elements:
Print index: 2. value: 100
Print index: 3. value: 101
The array elements in fact:
Print index: 2. value: 333
Print index: 3. value: 334
When `callbackfn` of `forEach` called `push` method, it maybe  reallocate the memory.
It maybe lead the `forEach` method referring overdue data.
> [Done]Update the  array#forEach implement

- std/portable/index.d.ts
- std/portable/index.js
* more safe `load`/`save`
* add `memory.reset` and `memory.fill`
* add `isDefined` and `isConstant`
* fix `bool` min/max constants
> Improve portables

- src/builtins.ts
- tests/compiler/builtins.untouched.wat
- tests/compiler/std/string.optimized.wat
Switch to faster approach:
```ts
function abs<T>(x: T): T {
var y = x >> (sizeof<T>() * 8 - 1); // actually 31 or 63
return (x + y) ^ y;
}
```
instead:
```ts
function abs<T>(x: T): T {
return x < 0 ? 0 - x : x;
}
```
This produce faster execution on Firefox. Also provide better constant folding and other general optimizations. Bench fiddle:
https://webassembly.studio/?f=5loa6qxs4ed
Results for Firefox 65.0b10:
```
original abs::i32: 25ms
new abs::i32: 18ms
```
On Chrome this pretty the same.
**TODO**
> Improve builtin abs for integers

- std/assembly/index.d.ts
- std/assembly/internal/typedarray.ts
- std/assembly/typedarray.ts
- tests/compiler/builtins.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.ts
- tests/compiler/std/typedarray.untouched.wat
This is a very big resubmission of the `TypedArray` prototype functions in the std lib. A lot of these changes were requested by @MaxGraey, and I fixed the exported types in the `/std/index.d.ts` file.
Thank you very much for this wonderful contribution to the web.
> Giant TypedArray refactor

- std/assembly/index.d.ts
Try to eliminate "Cannot find global `TypedPropertyDescriptor`" error
> Improve decorator declarations

- NOTICE
- src/glue/binaryen.d.ts
- src/module.ts
Extended `_BinaryenAddMemoryImport` and `_BinaryenSetMemory` functions with `shared: bool` argument
This will configure WASM memory as shared.
> Added shared memory support in binaryen definition

- src/ast.ts
- src/compiler.ts
- src/extra/ast.ts
- src/parser.ts
- src/resolver.ts
- src/types.ts
- tests/compiler/nonNullAssertion.optimized.wat
- tests/compiler/nonNullAssertion.ts
- tests/compiler/nonNullAssertion.untouched.wat
- tests/parser/nonNullAssertion.ts
- tests/parser/nonNullAssertion.ts.fixture.ts
Similar to https://github.com/AssemblyScript/assemblyscript/pull/235, but implemented as another kind of assertion.
> Implement non-null assertions

- src/ast.ts
- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/parser.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/call-super.optimized.wat
- tests/compiler/call-super.ts
- tests/compiler/call-super.untouched.wat
Passes a simple test and implements quite a few related checks. Still possible that not every single edge case is covered, but having this now and fixing any bugs as we go appears reasonable, considering that class support is still in the works anyway.
> Implement calls to 'super()'

- cli/asc.json
- package-lock.json
- package.json
- src/builtins.ts
- src/compiler.ts
- src/glue/binaryen.d.ts
- src/index.ts
- src/module.ts
- src/program.ts
- src/util/bitset.ts
- src/util/index.ts
- std/assembly/memory.ts
- tests/compiler/number.untouched.wat
- tests/compiler/std/allocator_arena.untouched.wat
- tests/compiler/std/array-literal.untouched.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/arraybuffer.untouched.wat
- tests/compiler/std/dataview.untouched.wat
- tests/compiler/std/gc-array.untouched.wat
- tests/compiler/std/static-array.untouched.wat
- tests/compiler/std/string-utf8.untouched.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/typedarray.untouched.wat
This PR updates Binaryen to latest and adds definitions and logic to support bulk memory operations.
* If `--enable bulk-memory` is specified, native `memory.copy` and `memory.fill` are emitted
* By default, the compiler falls back to our implementations of `memmove` and `memset` as usual
* This doesn't bother with `memory.init` and `memory.drop` yet.
> Implement bulk memory operations

- std/assembly/internal/sort.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
Default comparator was not tested well. So now use actually `comparator<string>()` instead external `(a, b) => (a > b) - (a < b)` and fix special cases for this comparison.
> Fix default comparator for strings

- cli/asc.json
- src/builtins.ts
- src/compiler.ts
- src/index.ts
- std/assembly/builtins.ts
- std/portable/index.js
This PR puts atomic operations behind `--enable threads`. Also renames the `Atomic.*` namespace to lower case so it blends in well with other intrinsics (even though `atomic.*` are actually deferred).
> Put atomics behind a feature flag

- cli/asc.js
- cli/asc.json
- src/compiler.ts
- src/index.ts
**CHANGES**
- `sharedMemory` option added to the compiler
Since shared memory needs mandatory max memory size, `sharedMemory` option accept a positive integer. 
| value  | meaning |
| ------------- | ------------- |
|`0` (default)| non shared memory|
|`+ve integer > 0` | enable shared memory and set max shared memory size|
- Feature is behind the flag `--enable threads`
> Shared memory support added to compiler

- NOTICE
- tests/compiler/wildcard-export.optimized.wat
- tests/compiler/wildcard-export.ts
- tests/compiler/wildcard-export.untouched.wat
relates to #27
relates to #249
relates to #489
opens #498
As the title states! This creates a new test for the new `export *` support 😄
> Added a test for wildcard exports

- src/builtins.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
- tests/compiler/builtins.optimized.wat
- tests/compiler/builtins.ts
- tests/compiler/builtins.untouched.wat
This PR adds two new builtins to statically evaluate type conditions that would be otherwise impossible to check for.
fixes #502
> Add isFunction and isNullable builtins

- bin/asc
- package-lock.json
- package.json
Since the compiler relies on assertions heavily while it isn't that rare to hit one, and having to deal with issues regularly that show useless stacktraces referring to dist files only, I figured that it makes sense to ship source map support by default.
Afaik this still doesn't solve the same problem when dealing with stack traces from WebAssembly Studio, because source maps aren't picked up there for some reason. Any ideas why this isn't working?
> Enable source maps out of the box

- std/assembly/index.d.ts
- std/assembly/internal/typedarray.ts
- std/assembly/typedarray.ts
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.ts
- tests/compiler/std/typedarray.untouched.wat
> Implement TypedArray#forEach

- std/assembly/math.ts
- std/portable/index.d.ts
- std/portable/index.js
+ `ASC_SHRINK_LEVEL` wrapper for `Mathf.tan`
+ `isNullable` & `isFunction` for portables
> Add sincos polyfill for portables

- src/parser.ts
This PR corrects parsing of e.g. `arr.reduce<i32>((a, b) => a + b, 0)`, which previously parsed the inner arrow function body as `a + b, 0`, resulting in just one argument to `.reduce<i32>(...)` etc.
fixes #543
> Fix arrow function body parsing precedence

- bin/asc
- bin/asinit
- cli/asc.json
- cli/util/options.js
- src/parser.ts
- src/types.ts
- tests/compiler.js
- tests/compiler/nonNullAssertion.untouched.wat
- tests/compiler/std/array-access.untouched.wat
- tests/compiler/std/array-literal.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/arraybuffer.optimized.wat
- tests/compiler/std/arraybuffer.untouched.wat
- tests/compiler/std/gc-array.optimized.wat
- tests/compiler/std/gc-array.untouched.wat
- tests/compiler/std/hash.untouched.wat
- tests/compiler/std/pointer.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/symbol.optimized.wat
- tests/compiler/std/symbol.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
This PR addresses a probable cause for the `Type 'Foo' is not assignable to type 'Foo'` issue. See also [this comment](https://github.com/AssemblyScript/assemblyscript/issues/539#issuecomment-473518110).
most likely fixes #539 / cc @vgrichina
> Use fully qualified names in generic types

- std/assembly/string.ts
- tests/compiler/number.optimized.wat
- tests/compiler/number.untouched.wat
- tests/compiler/std/array-access.optimized.wat
- tests/compiler/std/array-access.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/string-utf8.optimized.wat
- tests/compiler/std/string-utf8.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.ts
- tests/compiler/std/string.untouched.wat
Fix this cases
```ts
assert(!!"" == false);
assert(!!"\0" == true);
assert(!!"a" == true);
```
> Fix casting to bool for strings

- package-lock.json
- package.json
- src/builtins.ts
- src/decompiler.ts
- src/glue/binaryen.d.ts
- src/module.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
This PR updates Binaryen to v77.0.0-nightly.20190407 and incorporates their latest changes. In particular:
* There's a new argument to `BinaryenSetMemory` indicating passive segments
* Anything `AtomicWake` has been renamed to `AtomicNotify` and
* `i32.atomic.notify` and `i64.atomic.notify` have been collapsed to just `atomic.notify`, which in turn makes our builtin `atomic.notify<T>` non-generic, plus removing the `i32.` and `i64.` versions.
Should also unbreak WebAssembly Studio when using AssemblyScript, once dist files have been updated.
> Update Binaryen to latest

- NOTICE
- cli/asc.d.ts
- cli/util/options.d.ts
I found this when using the options parser in as-pect and `asc.exports` disagreed with `util.parse`'s expected argument type `Config`.
> Move OptionDescription to utils/options so types agree

- std/assembly.json
- std/assembly/rt/index.d.ts
- std/assembly/rt/pure.ts
Currently IDE's can't resolve stdlib imports that aren't relative.  This uses the ts path compiler option to try to resolve non-relative paths with the stdlib. 
This also fixes two typing errors that IDE found.
> Added paths option to resolve stdlib imports in IDE's

- src/builtins.ts
- src/compiler.ts
- src/diagnostics.ts
- src/types.ts
- tests/compiler/assert-nonnull.optimized.wat
- tests/compiler/assert-nonnull.untouched.wat
- tests/compiler/retain-i32.optimized.wat
- tests/compiler/retain-i32.ts
- tests/compiler/retain-i32.untouched.wat
- tests/compiler/std/symbol.optimized.wat
- tests/compiler/std/symbol.untouched.wat
This PR replaces the previous `compileExpressionRetainType` functionality, that assumed `i32` in inference, with a special `Type.auto` alias of `Type.i32` that can be used by subsequent steps to determine whether inference is taking place.
Previously, using just `i32` as the contextual type could lead to issues like https://github.com/AssemblyScript/assemblyscript/issues/650 where the `load<T>` built-in didn't know whether it is being called as `var a = <i32>load<bool>` or `var a = load<bool>`, in turn leading to an inferred type of `i32` instead of `bool`. With the change, the `load<T>` built-in can simply check for `contextualType == Type.auto`.
Also reverts contextual flags for statements because there was essentially only one that can as well be handled as a parameter instead, so …
> Use a special 'auto' type in type inference

- std/assembly/index.d.ts
This is a really simple `index.d.ts` change. I left the general case intact just in case. This improves the developer experience by adding suggested field names in intellisense.
Documentation should be consistent with the wording used by the original function definition because it was copy pasted.
> [Feature] add offset overloads

- cli/asc.js
- src/compiler.ts
- src/index.ts
- src/program.ts
As mentioned in https://github.com/AssemblyScript/assemblyscript/issues/676, it is not possible to completely disable the use of the internal `abort` function, making it necessary to at least provide an alternative. This PR changes this by just emitting an `unreachable` instruction if the abort function has been disabled explicitly through `--use abort=`.
> Allow internal abort to be disabled

- src/compiler.ts
- tests/compiler/std/operator-overloading.untouched.wat
- tests/compiler/std/pointer.optimized.wat
- tests/compiler/std/pointer.untouched.wat
As reported in https://github.com/MaxGraey/bignum.wasm/issues/20 the compiler didn't yet attempt to inline all possible call sites (while emitting an AS224 warning), but this should be possible now by using the utility introduced with the runtime branch. Essentially, whenever a call is inlined, the locals used in operands are blocked right-to-left so other temps don't conflict.
> Utilize new inlining utility to potentially inline any call

- std/assembly/shared/typeinfo.ts
`Key` instead of `Value` for KEY_SIGNED and KEY_FLOAT docs
> Documentation fixes.

- cli/asc.js
Got the below errors, when executed command asc /Workspace/assemblyscript/tests/compiler/for.ts -t for.wast
The reason is that the asc command works improperly when using absolute path.
```typescript
asc /Workspace/assemblyscript/tests/compiler/for.ts -t for.wast
ERROR: Entry file '/Workspace/assemblyscript/tests/compiler/for.ts' not found.
at Object.main (/Users/peng/Workspace/assemblyscript/cli/asc.js:391:25)
at Object.<anonymous> (/Users/peng/Workspace/assemblyscript/bin/asc:21:26)
at Module._compile (internal/modules/cjs/loader.js:774:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
at Module.load (internal/modules/cjs/loader.js:641:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at Function.Module.runMain …
```
> 1. Asc command supported absolute path.

- cli/asc.js
As discovered in https://github.com/AssemblyScript/assemblyscript/issues/714 the respective call to `listFiles` in asc when a directory was provided with `--lib` missed the necessary second parameter, leading to the described issue.
> Fix missing argument when specifying a --lib directory

- src/compiler.ts
- tests/compiler/class-static-function.json
- tests/compiler/class-static-function.optimized.wat
- tests/compiler/class-static-function.ts
- tests/compiler/class-static-function.untouched.wat
This is my first pass at fixing #720.
Thoughts?
> [Fix] Static class callback fixes #720

- std/assembly/util/string.ts
- tests/compiler/binary.optimized.wat
- tests/compiler/std/libm.optimized.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/operator-overloading.optimized.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
> Fix unnecessary float to int cast for strtol

- std/assembly/typedarray.ts
- tests/compiler/std/dataview.optimized.wat
- tests/compiler/std/dataview.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
Seems these got lost somewhere within the runtime branch. fixes https://github.com/AssemblyScript/assemblyscript/issues/748
> Reintroduce unchecked indexed access on views

- src/compiler.ts
potentially fixes https://github.com/AssemblyScript/assemblyscript/issues/761
> Do not retain unmanaged allocations in generated ctors

- std/assembly/index.d.ts
This removes IDE errors when trying use the toString method on those primitive types.
> Add toString methods to Number and Boolean

- src/compiler.ts
As surfaced [here](https://github.com/AssemblyScript/assemblyscript/issues/761#issuecomment-522063315), this PR makes
```ts
function test<T>(): void {
}
test();
```
emit an error instead of hitting an assertion, since if `T` is not the type of a function parameter, it has not been and cannot be inferred, and is effectively `unknown` inside of the function body.
> Emit an error instead of aborting when inferring unused type parameters

- src/builtins.ts
fixes #808
Hasn't been caught earlier because the respective test is disabled, since the instructions errors on various versions of node.
> Fix v128.store input type

- lib/loader/README.md
- lib/loader/index.d.ts
- lib/loader/index.js
- lib/loader/tests/index.js
This PR updates the loader with the lessons learned in https://github.com/AssemblyScript/assemblyscript/pull/794 while trying to make accessing typed arrays faster.
In particular, this completely eliminates the need to `checkMem` and wraps buffers in `new TypedArray`s directly. The lesson here seems to be that JS engines optimize this extremely well, not actually allocating something but just passing around buffers with a type attached.
Consequently, the `I8`, ... `F64` properties have been removed since a) `checkMem` isn't there anymore to update them, and b) it can be expected that manually wrapping the buffer in `new TypedArray` achieves similar results in user code. The README has been updated accordingly.
Also adds typing for 64-bit integer arrays using BigInt.
cc @MaxGraey
> Update loader with what we've learned

- lib/loader/index.js
Benchmark results.
Firefox 69:
Chrome 77.0.3865.56:
Bench link: https://esbench.com/bench/5d6fb7144cd7e6009ef62769
* Note: unset Babel transpiration check button before run tests
> [Loader] Speedup __getArray

- std/assembly/math.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.untouched.wat
For motivation see [1](https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/base/utils/random-number-generator.h#L111) and [2](https://github.com/v8/v8/blob/master/src/base/utils/random-number-generator.cc#L110)
> Rework Math.random

- src/parser.ts
- tests/parser/function-type.ts
- tests/parser/function-type.ts.fixture.ts
potentially fixes #822
As mentioned in https://github.com/AssemblyScript/assemblyscript/issues/822#issuecomment-528880236 we were missing a diagnostic here in the `(identifier)` case, which is ambiguous in that it can be either a parenthesized or a function type without parsing further. The fix is a bit awkward because the parser cannot look ahead more than one token, so it remembers the potentially erroneous parameter and issues the diagnostic once it is sure that it is dealing with a function type. Also adds parameters with an omitted type to the AST fwiw (serialization purposes maybe).
> Fix missing TS1110 on function signatures with one parameter

- src/compiler.ts
- src/resolver.ts
- tests/compiler/resolve-ternary.optimized.wat
- tests/compiler/resolve-ternary.ts
- tests/compiler/resolve-ternary.untouched.wat
- tests/resolve-ternary.json
Fixes
```ts
function FF(x: i32): i32 { return x; }
function GG(x: i32): i32 { return x + 2; }
var b = false;
assert(
(b ? FF : GG)(1).toString()
==
"3"
);
```
not compiling, even though
```ts
const FF = (x: i32): i32 => x;
const GG = (x: i32): i32 => x + 2;
...
```
compiles.
> Properly resolve function type from function name

- src/definitions.ts
the generated d.ts for
```ts
export function add(x: i32, y: i32): i32 {
return x + y;
}
export { add as addI32 }
```
was
```ts
declare module ASModule {
type i8 = number;
type i16 = number;
type i32 = number;
type u8 = number;
type u16 = number;
type u32 = number;
type f32 = number;
type f64 = number;
type bool = any;
export function add(x: i32, y: i32): i32;
export const addI32 = typeof add; // ERROR!
}
export default ASModule;
```
but it should be
```ts
declare module ASModule {
// ...
export function add(x: i32, y: i32): i32;
export const addI32: typeof add;
}
export default ASModule;
```
This pull request fixes this error.
> fix errors when generating definitions for export alias

- src/compiler.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/resolve-elementaccess.json
- tests/compiler/resolve-elementaccess.optimized.wat
- tests/compiler/resolve-elementaccess.ts
- tests/compiler/resolve-elementaccess.untouched.wat
fixes https://github.com/AssemblyScript/assemblyscript/issues/841
This represents the indexed access overloads as a new `IndexSignature` element, so `lookupElementAccess` etc. can return the actual element instead of deviating from all the other handlers.
> Represent indexed access with a typed element

- src/compiler.ts
- src/resolver.ts
- tests/compiler/typeof.json
- tests/compiler/typeof.optimized.wat
- tests/compiler/typeof.ts
- tests/compiler/typeof.untouched.wat
This PR implements `typeof` by emulating what JS/TS would do ([see also](https://github.com/AssemblyScript/assemblyscript/pull/783)). As such, it's not particularly accurate, for example
* `typeof null == "object"` even though AS would compile a lone `null` without class context as `usize`
* `typeof SomeClassEnumOrNamespace == "object"` even though that's not actually a runtime object in AS
* `typeof doesntEvenExist == "undefined"` even though that's not a type in AS (ofc also true for `object`)
* there's just `"number"`
plus
* `typeof someAnyref == "anyref"` since [MDN says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Description) "Host object (provided by the JS environment) - Implementation-dependent." Not sure if that applies here, though.
> Implement typeof expressions

- std/assembly/builtins.ts
- std/assembly/index.d.ts
Missed the second argument to `v128.narrow<T>`. Found this while updating the docs. Not caught by tests due to using asm-style instructions deferring there which works regardless.
> Fix SIMD narrowing definition

- src/compiler.ts
- std/assembly/array.ts
- std/assembly/fixedarray.ts
- std/assembly/index.d.ts
- std/assembly/map.ts
- std/assembly/set.ts
- std/portable/index.d.ts
- std/portable/index.js
- tests/compiler/assert-nonnull.optimized.wat
- tests/compiler/assert-nonnull.untouched.wat
- tests/compiler/resolve-access.optimized.wat
- tests/compiler/resolve-access.untouched.wat
- tests/compiler/retain-release-sanity.optimized.wat
- tests/compiler/retain-release-sanity.untouched.wat
- tests/compiler/std/array-access.optimized.wat
- tests/compiler/std/array-access.untouched.wat
- tests/compiler/std/array-literal.optimized.wat
- tests/compiler/std/array-literal.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/static-array.optimized.wat
- tests/compiler/std/static-array.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
This is an implementation of the suggestion made in https://github.com/AssemblyScript/assemblyscript/issues/853 in that it removes the need to use non-standard `Array.create<T>(length > 0)` over `new Array<T>(length > 0)` while moving that check to actually accessing an array's elements, throwing if there's an unexpected `null` in it as a result of not properly initializing it.
> Improve holey array handling and remove Array.create

- src/resolver.ts
- tests/compiler/resolve-propertyaccess.json
- tests/compiler/resolve-propertyaccess.optimized.wat
- tests/compiler/resolve-propertyaccess.ts
- tests/compiler/resolve-propertyaccess.untouched.wat
I recently noticed that there's something missing when resolving property accesses, so I added a test and found an issue with enum values. However, I think this still doesn't catch the issue I noticed initially which had something to do with resolving `i32.MAX_VALUE` somewhere. Going to investigate further.
> Add resolve-propertyaccess test

- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.ts
- tests/compiler/std/math.untouched.wat
Due to a [regression in Math.hypot](https://bugs.chromium.org/p/v8/issues/detail?id=9546) in v8 7.7 (node 12.11.0), [some of the std/math tests](https://github.com/AssemblyScript/assemblyscript/pull/871/commits/cb69181782f4905cd72dc039ac4d96b0ebfdd7cf#diff-d0b06574e5eed6802cbc0a204227084dR1644-R1652), that also run against node, are currently failing. This PR temporarily disables the JS testing for the edge cases in question. The bug is fixed in v8 7.8, so once latest node uses that, the tests can be enabled again.
> Temporarily disable testing Math.hypot against node/V8

- NOTICE
- README.md
- lib/lint/formatters/asFormatter.js
- lib/lint/rules/asTypesRule.js
- lib/lint/rules/asVariablesRule.js
- lib/lint/rules/internal/asInternalCaseRule.js
- lib/lint/rules/internal/asInternalDiagnosticsRule.js
- lib/lint/src/rules/asTypesRule.ts
- tests/compiler/builtins.ts
- tests/compiler/std/array.ts
- tests/compiler/std/typedarray.ts
Fixes #819.
Also makes the linter detect arrow function return types that are now unnecessary, and fixes those cases.
Also I think `npm clean` should be `npm run clean` in the readme, so fixed that as well.
> Allow omitting return type in callback arrow functions

- package-lock.json
- package.json
- tests/compiler.js
Given the `--parallel` option, the compiler test suite can now spawn one process per logical CPU core and split the tests among them. The goal was to make this 100% interchangeable with a normal run, producing the same output except test ordering. Reduces the time of `npm run test:compiler` from 32 to <del>17</del> 13 seconds on my machine using <del>16</del> 7 workers.
> Add option to run compiler tests in parallel

- src/ast.ts
- src/compiler.ts
- src/diagnostics.ts
- src/flow.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/duplicate-identifier.json
- tests/compiler/duplicate-identifier.ts
Related: https://github.com/AssemblyScript/assemblyscript/pull/797
This PR extends "Duplicate identifier: X" errors by also printing the range of the already existing identifier. This isn't currently possible for scoped locals (`let`, `const` in a block) that use a shared declaration (multiple names share the same local), but works for any `var`, class member, namespace member etc. Also fixes the assertions triggered previously.
> Emit related ranges for duplicate identifiers

- std/assembly/array.ts
- std/assembly/util/string.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
Now during join arrays of objects we always call `toString`. Also slightly improve join array of strings
> Fix join objects. Unify join arrays & objects

- std/assembly/map.ts
- std/assembly/set.ts
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/set.untouched.wat
- tests/compiler/std/symbol.optimized.wat
- tests/compiler/std/symbol.untouched.wat
I expect this shouldn't decrease performance because division by constant usually transform to [wide multiplication + shift](https://en.wikipedia.org/wiki/Division_algorithm#Division_by_a_constant).
Close #902
> Use integer fractions for FILL_FACTOR & FREE_FACTOR in Map/Set

- src/builtins.ts
- src/types.ts
As reported in https://github.com/AssemblyScript/assemblyscript/issues/894 the current checks in `changetype` aren't sufficient. This PR adds a proper check.
fixes https://github.com/AssemblyScript/assemblyscript/issues/894
> Improve changetype check

- std/portable/index.js
This normalize `Array#sort()` for portable so now:
```ts
[0, -0, -1, NaN, Infinity, 2, 123].sort()
```
output (which the same as AS):
```ts
[ -1, -0, 0, 2, 123, Infinity, NaN ]
```
instead:
```ts
[ -1, 0, -0, 123, 2, Infinity, NaN ]
```
This also [speed-up](https://esbench.com/bench/5d9251b84cd7e6009ef627ef) array's sort
> sync AS and portable behaviour for Array#sort with default comparator

- src/ast.ts
- src/builtins.ts
- tests/compiler/builtins.optimized.wat
- tests/compiler/builtins.ts
- tests/compiler/builtins.untouched.wat
- tests/compiler/mandelbrot.optimized.wat
- tests/compiler/mandelbrot.untouched.wat
This resolves some issues with literals being the first argument to type-inferred builtins as reported in https://github.com/AssemblyScript/assemblyscript/issues/896. There are other edge cases this doesn't cover (for example `min(someF32Expr, someF64Expr)`), but while trying to implement a proper fix I hit road blocks in the resolver that must be investigated in more detail.
> Improve generic builtin type inference with multiple parameters

- src/compiler.ts
Fixes https://github.com/AssemblyScript/assemblyscript/issues/912
What happened there is that `resolver.currentThisExpression` may become invalid before use.
> Fix 'this' confusion when inferring generic calls

- lib/loader/README.md
- lib/loader/index.d.ts
- lib/loader/index.js
- lib/loader/tests/index.html
- lib/loader/tests/index.js
This makes `loader.instantiate` asynchronous to align with `WebAssembly.instantiate` and replaces `loader.instantiateBuffer` with `loader.instantiateSync` accepting both a pre-compiled module or a buffer, just like `loader.instantiate`.
> Align loader API with WebAssembly API

- std/assembly/rt/index.d.ts
- std/assembly/rt/pure.ts
- std/assembly/rt/stub.ts
- tests/compiler/number.optimized.wat
- tests/compiler/number.untouched.wat
- tests/compiler/resolve-binary.optimized.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/resolve-elementaccess.optimized.wat
- tests/compiler/resolve-elementaccess.untouched.wat
- tests/compiler/rt/stub-realloc.optimized.wat
- tests/compiler/rt/stub-realloc.untouched.wat
- tests/compiler/std/static-array.optimized.wat
- tests/compiler/std/static-array.untouched.wat
+ also make `__reset` exportable
> Optimize stub's realloc

- src/compiler.ts
- tests/compiler/features/simd.optimized.wat
- tests/compiler/features/simd.untouched.wat
- tests/compiler/namespace.optimized.wat
- tests/compiler/namespace.ts
- tests/compiler/namespace.untouched.wat
fixes https://github.com/AssemblyScript/assemblyscript/issues/575
We already had special logic for enum members but were missing namespaces, so this generalizes the `currentParent` to any element and fixes the issue.
> Properly resolve namespace siblings

- NOTICE
- src/definitions.ts
Export ExportsWalker to allow building custom walkers for analysis tools.
Allow an option to asc.main to get called with the Program object to
facilitate building custom CLIs on top of asc that call their own analysis
logic.
> Allow using a custom analyzer

- src/compiler.ts
- src/flow.ts
Some minor flow stuff discovered while toying around with __retain/__release elimination, which ultimately didn't materialize.
> Minor flow improvements

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- lib/loader/package.json
- package.json
This PR contains the initial preparation work to start publishing to npm. Idea is:
* Create a `release` branch that is always up to date with the tip of our releases
* Once a day
* Merge `master` into `release`
* Build and commit dist files
* Obtain the current version from `package.json`
* Check if the respective tag (with a prepended "v") does exist
* If it exists, make a nightly of the form `v$VERSION-nightly.YYYYMMDD`
* If it does not exist, make a release of the form `v$VERSION`
* Push dist files back to `release` and create the tag
* Publish to npm (not yet enabled)
* Publish to GH package registry (not yet enabled)
This gives us:
* To bump the version, all we have to do is edit `package.json`
* If the dist files at the tip of our releases are the same as those we just built, the …
> Publish preparations

- .github/workflows/publish.yml
This PR is what's necessary to enable publishing to npm and gpr. Unfortunately, whether this will work or not is hard to test, so I'm wondering if we should just merge it and see what happens. If anything goes wrong, we can still learn from it and update to 0.9.0 or something. Objections?
> Enable publishing

- .github/workflows/publish.yml
- README.md
- cli/asc.js
- index.js
- lib/loader/README.md
- lib/loader/package.json
- package.json
- scripts/release.js
* Fixes classic misplaced quote
* Specifies `skipIgnore` to ts-node in case the compiler lives inside of `node_modules`
* Makes TypeScript a normal dependency along ts-node for master where there are no dist files
> Even more publish fixes

- bin/asc
- cli/asc.js
- cli/util/find.d.ts
- cli/util/find.js
- cli/util/utf8.d.ts
- cli/util/utf8.js
- index.js
- package-lock.json
- package.json
- scripts/release.js
This PR cleans up release dependencies so all we are depending on is `binaryen` and `long`, which both don't have dependencies on their own and are controlled by us. While not ultimately necessary, this reduces the surface area for what can go wrong to a minimum and makes installing the package as fast as it gets.
Also incorporates https://github.com/AssemblyScript/assemblyscript/pull/947.
> Clean up release dependencies

- src/compiler.ts
- tests/compiler/closure.json
- tests/compiler/closure.optimized.wat
- tests/compiler/closure.ts
As pointed out in https://github.com/AssemblyScript/assemblyscript/issues/954, while closed-over locals can be properly resolved meanwhile, we were missing an error when we see one. Still not great, but it really shouldn't yield a validation error.
> Emit an error on not implemented closure

- NOTICE
- src/flow.ts
- src/module.ts
- src/program.ts
- tests/compiler/features/reference-types.ts
- tests/compiler/features/reference-types.untouched.wat
```ts
declare function external(a: anyref): anyref;
export function internal(a: anyref): anyref {
// is an anyref
const b = external(a);
return b;
}
```
Right now if you try to use an anyref as a variable declaration it barfs with:
```
ERROR: concrete type expected
at c.getTempLocal
```
This solves it by making the compiler aware that anyrefs can be stored as locals
Keywords: reference types, reference-types, gc
> Support anyref variable declartions as Wasm locals

- std/assembly/array.ts
- tests/compiler/binary.optimized.wat
- tests/compiler/i64-polyfill.optimized.wat
- tests/compiler/mandelbrot.optimized.wat
- tests/compiler/resolve-access.optimized.wat
- tests/compiler/retain-release-sanity.optimized.wat
- tests/compiler/retain-release-sanity.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/date.optimized.wat
- tests/compiler/std/libm.optimized.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/mod.optimized.wat
- tests/compiler/std/static-array.optimized.wat
- tests/compiler/std/static-array.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/unary.optimized.wat
- this will be more optimal
- also previous approach allowed `arr[-1] = x` without throwing OOB trap which is wrong
> improve Array's __set method

- std/assembly/math.ts
- tests/compiler/binary.untouched.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/libm.optimized.wat
- tests/compiler/std/libm.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.untouched.wat
- tests/compiler/std/operator-overloading.optimized.wat
- tests/compiler/std/operator-overloading.untouched.wat
See
https://git.musl-libc.org/cgit/musl/commit/?id=688d3da0f1730daddbc954bbc2d27cc96ceee04c
https://git.musl-libc.org/cgit/musl/commit/?id=b023c03b574acdfd73418314a5dcaa83e5cea5a0
Before:
`Mathf.exp(-NaN) == 0`
With fixes:
`Mathf.exp(-NaN) == -NaN`
> [math] sync with latest musl updates

- lib/loader/index.d.ts
- lib/loader/package.json
"@types/webassembly-js-api" deprecated and cause to conflicts since TS provide own webassembly api definitions.
> Remove @types/webassembly-js-api from loader

- .github/workflows/publish.yml
- .gitignore
- cli/asc.js
- cli/asc.json
- package-lock.json
- package.json
- scripts/postpublish-files.json
- scripts/postpublish.js
- scripts/prepublish.js
- src/builtins.ts
- src/common.ts
- src/compiler.ts
- src/flow.ts
- src/glue/binaryen.d.ts
- src/module.ts
- src/program.ts
- src/types.ts
- tests/compiler/bool.optimized.wat
- tests/compiler/builtins.optimized.wat
- tests/compiler/call-inferred.optimized.wat
- tests/compiler/class-static-function.optimized.wat
- tests/compiler/features/reference-types.optimized.wat
- tests/compiler/function-expression.optimized.wat
- tests/compiler/getter-call.optimized.wat
- tests/compiler/getter-setter.optimized.wat
- tests/compiler/inlining.optimized.wat
- tests/compiler/instanceof.optimized.wat
- tests/compiler/portable-conversions.optimized.wat
- tests/features.json
This PR includes improvements made in various blocked or otherwise delayed PRs that are generally useful to have in master right now, including
* Updates to publishing
* Custom pass order & converge option
* Binaryen API bindings & exnref integration
* Due refactoring
> Forward useful improvements within blocked PRs

- src/ast.ts
- src/compiler.ts
- src/extra/ast.ts
- src/parser.ts
- src/resolver.ts
- tests/compiler/new.json
- tests/compiler/new.optimized.wat
- tests/compiler/new.ts
- tests/compiler/new.untouched.wat
This fixes https://github.com/AssemblyScript/assemblyscript/issues/932 by adding more specific code to parse `new` expressions, also handling `new SomeClass` without parenthesis.
As it stands, the parsing is not quite JS-like in that it expects an identifier or series of identifiers (combined to a property access) as the target, assuming that anything else (like `new (getSomeCtor())`) can't be constructed anyway in AS.
> Fix 'new' parsing & allow omitting parenthesis

- .github/workflows/ci.yml
- NOTICE
Tests the compiler on Windows as a separate CI job. This is designed to catch "bash-isms" that could otherwise sneak in, rather than provide full Windows coverage. Thus it only tests the stable node version.
On Linux, nvm is used to determine the current stable version. Since that does not work on Windows, the job uses [nvm-windows](https://github.com/coreybutler/nvm-windows) as a substitute. That project is written in Golang, so a pre-compiled binary is downloaded and invoked directly.
> CI: run compiler tests on Windows

- .github/workflows/ci.yml
see: https://github.com/AssemblyScript/assemblyscript/issues/989
> Temporarily pin node-v8 to last known good build

- src/compiler.ts
- tests/compiler/logical.ts
- tests/compiler/logical.untouched.wat
This fixes a bug where, when simplifying compilation of logical expressions due to only being interested in true or false, like in
```ts
if (someI64 >> 63 && someBool) ...
```
the result type of the inner logical expression was still set to the left type (here i64), even though earlier code correctly set it to bool, leading to a validation error down the road.
cc @MaxGraey: Does this fix the problem you mentioned?
> Fix type confusion in logical expressions

- NOTICE
- cli/asc.js
- src/tsconfig.json
Fixes #978. src and transforms will now have the same compile target so
transforms can consume classes exported by src.
> Use ES2016 as target for src and transforms

- std/assembly/map.ts
- std/assembly/set.ts
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/map.ts
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/set.ts
- tests/compiler/std/set.untouched.wat
1. Fix the about map.keys and map.values and set.values.
Because of initializing the array of keys and value with size, so using `push` will append data to array.
2. Add test cases for map.keys, map.values and set.values.
> [Bug fix] Fix the bug about map.keys and map.values

- NOTICE
- std/assembly/index.d.ts
This will help in the following scenarios:
```typescript
function bar(): bool {
unreachable();
return false; // typescript will report "Unreachable code detected"
}
function getImpl(implId: i32): Impl {
switch ( implId ) {
case 1: return new Impl1();
case 2: return new Impl2();
default: unreachable();
}
// typescript won't complain about missing return statement here.
}
```
> Change type definitions for `unreachable` to make typescript recognize it as an end point

- src/compiler.ts
The existing assertion checks that we don't miss a retain when calling super, setting up the class instance's memory, but this misses that the class can be `@unmanaged` so there isn't anything to retain.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1013
> Fix assertion hit by unmanaged super calls

- src/compiler.ts
- tests/compiler/infer-array.json
- tests/compiler/infer-array.optimized.wat
- tests/compiler/infer-array.ts
- tests/compiler/infer-array.untouched.wat
An initial implementation of inferring array literals in auto contexts from their first element, as proposed in https://github.com/AssemblyScript/assemblyscript/issues/1007. Does not yet handle `null`s.
> Infer array type from first element in auto context

- src/compiler.ts
- src/flow.ts
- tests/compiler/assert-nonnull.untouched.wat
- tests/compiler/retain-return.json
- tests/compiler/retain-return.optimized.wat
- tests/compiler/retain-return.ts
- tests/compiler/retain-return.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/symbol.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
As reported in https://github.com/AssemblyScript/assemblyscript/issues/1026 there is an issue when a managed reference is returned from function expressions using just a single expression.
To fix this, I ultimately decided to unify preparation of potentially managed return values by reusing autorelease undo functionality originally implemented for branch unification. As a side-effect this also gets rid of various unnecessary retain/release pairs whenever the undo succeeded.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1026
> Fix managed function expression return

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/resolver.ts
- tests/compiler/extends-recursive.json
- tests/compiler/extends-recursive.optimized.wat
- tests/compiler/extends-recursive.ts
- tests/compiler/extends-recursive.untouched.wat
- tests/compiler/extends-self.json
- tests/compiler/extends-self.ts
This fixes two problems:
1. As reported in https://github.com/AssemblyScript/assemblyscript/issues/1024, resolving the base class prior to constructing this class can lead to situations where the base class already triggered resolving this class, in turn hitting an assertion.
2. A diagnostic was missing for when a class is directly or indirectly referencing itself in the extends chain.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1024
> Fix recursive extends/aggregation

- src/builtins.ts
- src/compiler.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/call-super.optimized.wat
- tests/compiler/call-super.untouched.wat
- tests/compiler/extends-baseaggregate.json
- tests/compiler/extends-baseaggregate.optimized.wat
- tests/compiler/extends-baseaggregate.ts
- tests/compiler/extends-baseaggregate.untouched.wat
- tests/compiler/extends-recursive.optimized.wat
- tests/compiler/extends-recursive.untouched.wat
- tests/compiler/inlining.optimized.wat
- tests/compiler/inlining.untouched.wat
As reported in https://github.com/AssemblyScript/assemblyscript/issues/1030 there is an issue with premature layout when resolving classes. This is due to the recursion missing the case where a base class's members (not their base) again trigger resolving a derived class with a base class that isn't fully layed out yet (around 4 corners?), in turn prematurely laying out the derived class with missing base fields.
This is an attempt to solve this by yielding within the recursion (but never on the first API call) instead of doing an improper layout, then triggering finalization as soon as the base class is fully layed out, essentially abusing the execution stack to roll back the recursion (by adding another recursion). I must admit though that this solution feels kinda wild west and there's …
> Fix premature layout in resolveClass recursion

- lib/sdk/README.md
- lib/sdk/index.js
- lib/sdk/tests/index.html
- package-lock.json
- package.json
- scripts/build-sdk.js
- scripts/update-constants.js
- src/builtins.ts
- src/compiler.ts
- src/glue/binaryen.d.ts
- src/module.ts
- src/types.ts
- tests/compiler/features/reference-types.optimized.wat
- tests/compiler/features/reference-types.ts
- tests/compiler/features/reference-types.untouched.wat
In celebration of the new year, this updates our Binaryen bindings to include fireworks.
> Update Binaryen for 2020

- NOTICE
This makes the NOTICE file a lot easier to deal with by linking to the respective licenses instead of concatenating stuff over and over again. Did a check on the base license texts to be sure and these match 1:1.
> Update NOTICE file

- src/compiler.ts
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
This should fix the release issue reported in #1039 and worked around in #1040. What happened there was that when an autorelease was undone in an inner flow, the outer flow would still append a release in inline contexts due to checking local flags in the parent instead of the child flow. This now walks the locals of the parent flow and checks against states in the child flow.
fixes #1039
fixes #1040
> Fix undone autorelease in inlined context

- std/assembly/math.ts
- tests/compiler/binary.untouched.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/libm.optimized.wat
- tests/compiler/std/libm.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.ts
- tests/compiler/std/math.untouched.wat
- tests/compiler/std/operator-overloading.optimized.wat
- tests/compiler/std/operator-overloading.untouched.wat
1) Fix `Math.pow(-0, 0.5)` => `0` instead `-0`.
2) Remove Math.pow(x, -0.5) because it could lead to precision loss.
> Minor fix for fast path for Math.pow. (-0) ** 0.5 should be 0 instead -0

- std/assembly/typedarray.ts
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.ts
- tests/compiler/std/typedarray.untouched.wat
> Fix wrong bound checks in TypedArray.wrap

- src/compiler.ts
- src/program.ts
- tests/compiler/exports.optimized.wat
- tests/compiler/exports.untouched.wat
- tests/compiler/extends-recursive.optimized.wat
- tests/compiler/extends-recursive.untouched.wat
This fixes a naming issue only present for instance fields of explicitly exported classes. These were added with truncated internal names.
> Fix field export naming

- src/compiler.ts
- src/program.ts
This is a follow-up to https://github.com/AssemblyScript/assemblyscript/commit/1bf41409d9e376a41a69a9a4f2163cf5b1c86339, splitting the compilation of field respectively property getters and setters.
> Split compilation of getters and setters

- cli/asc.d.ts
- cli/asc.js
- tests/browser-asc.js
The `asc.compileString` API was using a wrong options interface. This PR renames these to better reflect their purpose, and adds the correct options interface.
fixes: https://github.com/AssemblyScript/assemblyscript/issues/1019
> Fix compileString options in asc.d.ts

- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/diagnostics.ts
- tests/compiler/instanceof.ts
This makes pedantic diagnostics use its own category and so far adds diagnostics for:
* **Expression compiles to a dynamic check at runtime.**
If an `instanceof` check cannot be evaluated statically and falls back to RTTI.
* **Indexed access may involve bounds checking.**
If an element access expression is not wrapped with `unchecked(...)`. This is not always true for user-defined overloads.
> Extend pedantic diagnostics

- package-lock.json
- package.json
This is a minor release we knew was coming by updating Binaryen after 0.9, which turned out to be not so dramatic, yet is good to do. Also fixes a couple things, with the last one potentially unbreaking some users.
* Fix truncated field export naming
* Fix `asc.compileString` definitions
* Update Binaryen
* Add a fallback for argumentsLength without mutable-globals
> Slice version 0.9.1

- cli/asc.json
- cli/util/options.js
The CLI options are becoming somewhat hard to grasp, so this PR reorders them and adds categories:
```
SYNTAX
asc [entryFile ...] [options]
EXAMPLES
asc hello.ts
asc hello.ts -b hello.wasm -t hello.wat
asc hello1.ts hello2.ts -b -O > hello.wasm
OPTIONS
General
--version, -v         Prints just the compiler's version and exits.
--help, -h            Prints this message and exits.
--noColors            Disables terminal colors.
Optimizations
--optimize, -O        Optimizes the module. Typical shorthands are:
Default optimizations   -O / -O3s
Make a release build    -O --noAssert
Make a debug build      --debug
Optimize for speed      -O3
Optimize for size       -O3z --converge
--optimizeLevel       How much to focus on optimizing code. [0-3]
--shrinkLevel         How much to focus on …
```
> Categorize CLI options

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/diagnostics.ts
- src/parser.ts
- src/tokenizer.ts
This fixes quite a bit of unnecessary diagnostic noise related to `INVALID` tokens, based on the example given by @MaxGraey :
```ts
export function getSpooky<👻>(): string {
return "boo";
}
```
In particular, if an `INVALID` token is seen and is part of a surrogate pair, the entire pair will be skipped instead of emitting two diagnostics. Also, the tokenizer now implicitly skips over invalid tokens aiding the parser. There's already a diagnostic anyway. Also fixes a bug in the parser emitting `null` on empty type parameter lists, which sometimes resulted in reparsing something that already emitted a diagnostic.
In the example above, this now results in 2 errors (invalid character, empty type parameter list) instead of spooky 13.
> Be more careful on invalid tokens

- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/resolver.ts
- std/assembly/array.ts
- tests/compiler/builtins.ts
- tests/compiler/infer-array.optimized.wat
- tests/compiler/infer-array.ts
- tests/compiler/infer-array.untouched.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/object.optimized.wat
- tests/compiler/std/object.ts
- tests/compiler/std/object.untouched.wat
This PR addresses the issues reported in https://github.com/AssemblyScript/assemblyscript/issues/1083, except that it doesn't yet disallow inferring `null` to `usize` if the contextual type is not a reference type as this would be a breaking change I'm not sure about yet.
Referencing the snippets of the original issue:
```ts
let arr1 = [null, "a"]; // should compile but produce error
```
This now compiles due to inferring logic skipping null literals, and applying the nullable flag afterwards.
```ts
let arr2 = [null];      // should produce error but compile
```
This now produces an error because `null` has been skipped and the final element type is `auto`. More of a side-effect that would play well with disallowing `null` in non-reference contexts, if we decide to go for that.
```ts
let …
```
> Fix special 'null' cases when inferring array literals

- src/compiler.ts
- tests/compiler/extends-recursive.optimized.wat
- tests/compiler/extends-recursive.untouched.wat
- tests/compiler/implicit-getter-setter.js
- tests/compiler/implicit-getter-setter.json
- tests/compiler/implicit-getter-setter.optimized.wat
- tests/compiler/implicit-getter-setter.ts
- tests/compiler/implicit-getter-setter.untouched.wat
This PR fixes an issue with generated implicit field setters of exported classes as reported in https://github.com/AssemblyScript/assemblyscript/issues/1101.
What happened there was that the use of `makeReplace` was incorrect in that it obtains temporary locals from the current function's flow, but there is no actual current function, hence no flow, for *generated* setters. Instead, such a function has exactly two locals, its parameters, of which one became overwritten with the old value due to a duplicate temp being picked, leading to an invalid load.
The fix applied here implements custom but otherwise identical replace logic, with a single temp local for the intermediate value.
> Fix local confusion in generated implicit setters

- src/compiler.ts
This should fix the issue reported in https://github.com/AssemblyScript/assemblyscript/issues/1105, caused by the resolve step when compiling `instanceof` not propagating contextual types.
> Fix lost contextual types in instanceof

- src/ast.ts
- src/builtins.ts
- src/compiler.ts
- tests/compiler/instanceof-class.json
- tests/compiler/instanceof-class.optimized.wat
- tests/compiler/instanceof-class.ts
- tests/compiler/instanceof-class.untouched.wat
This is an initial implementation of `instanceof CLASS` checks like
```ts
a instanceof Array
a instanceof Map
a instanceof Set
```
Does static checks where possible, except in upcast cases like
```ts
class Parent<T> {}
class Child<T> extends Parent<T> {}
var a: Parent<i32> = new Child<i32>();
if (a instanceof Child) {
...
}
```
where an internal helper, here named `Child~instanceof`, is generated and called, that checks against all possible concrete instance ids. For example, if there's a `Child<i32>` and a `Child<f32>` present in the module, both are valid according to the dynamic check. Dynamic checks are potentially costly if there are lots of instances of a generic class.
> Handle instanceof of entire classes

- src/compiler.ts
- tests/compiler/issues/1095.json
- tests/compiler/issues/1095.optimized.wat
- tests/compiler/issues/1095.ts
- tests/compiler/issues/1095.untouched.wat
- tests/compiler/retain-release-sanity.optimized.wat
- tests/compiler/retain-release-sanity.untouched.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.untouched.wat
- tests/compiler/std/symbol.untouched.wat
This PR fixes an issue caused by indexes of potential temporary locals in the RHS of a field assignment not being blocked preemptively. Also reorders the arguments to `makeReplace` to adhere to execution order fwiw.
fixes #1095
> Fix temp local confusion in field assignment

- package-lock.json
- package.json
- src/glue/binaryen.d.ts
- src/module.ts
* Added a `--tableBase` CLI option (like `--memoryBase`, but for tables)
* Support `x instanceof GenericClass`
* Update Binaryen to latest
* Fixed `null` related edge cases when inferring array literals
* Fixed several code generation issues
* Align `Map#set` and `Set#add` with the spec, returning `this`
* Fixed WASI import scheme to use `wasi_snapshot_preview1`
> Slice version 0.9.2

- NOTICE
- src/compiler.ts
- tests/compiler/enum.ts
Issue: https://github.com/AssemblyScript/assemblyscript/issues/574
If you tried to use a const enum with multiple members, you would receive a compilation failure.
This was because the compiler relied upon each enum value to be registered as a global value in order to determine what the next enum value was. As a result, when we inlined the enum values and did not register that global value, compilation would fail.
To fix this, I've changed this method around a bit to rely upon the last expression value used (held in `initExpr`) rather than trying to load from the global store.
I'm not sure why it was implemented the way it was originally- it's possible that there is some tradeoff involved here I'm unaware of which causes reading from the global store to be faster/more efficient than …
> Fix const enum compilation failure

- src/compiler.ts
- tests/compiler/class.optimized.wat
- tests/compiler/class.ts
- tests/compiler/class.untouched.wat
This PR fixes https://github.com/AssemblyScript/assemblyscript/issues/1119 by properly propagating contextual type arguments to programmatically generated constructors, so these are known to the respective instance flow when compiling instance field initializers.
> Propagate contextual type arguments to generated constructors

- src/program.ts
This is an attempt to fix https://github.com/AssemblyScript/assemblyscript/issues/1117 by removing an assertion and providing a better (local) identifier reference for the emitted diagnostic.
> Fix assertion on duplicate imported identifiers

- src/compiler.ts
- src/flow.ts
- src/parser.ts
So after wasting several days with a flow refactor that I had to scrap again due to spontaneous self ignition of the compiler, there's still something good coming out of it in that I managed to salvage a fix for the issues described in https://github.com/AssemblyScript/assemblyscript/issues/1139.
> Fix failing non-null checks

- src/resolver.ts
- tests/compiler/resolve-elementaccess.optimized.wat
- tests/compiler/resolve-elementaccess.ts
- tests/compiler/resolve-elementaccess.untouched.wat
As reported in #1141 the resolver missed that an index signature might become inherited from the base class, so this change makes it traverse through base classes until it finds one.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1141
> Use base index signature if inherited

- src/compiler.ts
- tests/compiler/extends-recursive.optimized.wat
- tests/compiler/extends-recursive.untouched.wat
- tests/compiler/resolve-nested.optimized.wat
- tests/compiler/resolve-nested.untouched.wat
This PR forces generation of constructors where necessary if a class has been explicitly exported. Also drive-by fixes missing related diagnostics that would otherwise not become triggered due to tree-shaking. While a relatively conservative fix, it's still good to have for the time being. See the linked issue for potential improvement ideas.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1150
> Ensure constructors of exported classes

- package-lock.json
- package.json
- src/index.ts
Fixes https://github.com/AssemblyScript/assemblyscript/issues/1157 by making the respective change backwards compatible to any 0.9.x.
> Fix unintentional breaking change and slice v0.9.4

- src/ast.ts
- src/builtins.ts
- src/compiler.ts
- src/definitions.ts
- src/extra/ast.ts
- src/flow.ts
- src/parser.ts
- src/program.ts
- src/resolver.ts
- tests/bootstrap/index.ts
This PR refactors the compiler sources with the intent to eliminate any redundant type assertions that might involve a redundant dynamic check at runtime when compiling to WebAssembly.
Typical patterns are
```ts
if (element.kind == ElementKind.FUNCTION) {
doSomething(<Function>element);
doSomethingElse(<Function>element);
}
```
which are nops in TS but upcasts in AS, where refactoring these to
```ts
if (element.kind == ElementKind.FUNCTION) {
let functionInstance = <Function>element;
doSomething(functionInstance);
doSomethingElse(functionInstance);
}
```
does just one dynamic check instead of two at the expense of an additional local that Binaryen will most likely collapse again.
Also makes relevant code a little more verbose as a side-effect, which some might find helpful to keep track …
> Eliminate redundant type assertions

- std/assembly/util/number.ts
- tests/compiler/number.optimized.wat
- tests/compiler/number.untouched.wat
- tests/compiler/resolve-access.optimized.wat
- tests/compiler/resolve-access.untouched.wat
- tests/compiler/resolve-binary.optimized.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/resolve-elementaccess.optimized.wat
- tests/compiler/resolve-elementaccess.untouched.wat
- tests/compiler/resolve-function-expression.optimized.wat
- tests/compiler/resolve-function-expression.untouched.wat
- tests/compiler/resolve-propertyaccess.optimized.wat
- tests/compiler/resolve-propertyaccess.untouched.wat
- tests/compiler/resolve-ternary.optimized.wat
- tests/compiler/resolve-ternary.untouched.wat
- tests/compiler/resolve-unary.optimized.wat
- tests/compiler/resolve-unary.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
It has almost the same performance:
https://webassembly.studio/?f=kmv06wf9xw
On Chrome 80:
```
decimalCount32_old: 1113ms
decimalCount32_new: 1073ms
```
But smaller bytecode size (188 vs 200 bytes)
> optimize decimalCount32/64 + minor refactoring in util/number

- std/assembly/index.d.ts
`StaticArray`s are `@sealed`, so declaring them in the `index.d.ts` file as `abstract` causes vscode to report errors when using the `StaticArray` `constructor`.
This pull request removes the `abstract` keyword to prevent users from experiencing confusion about how `StaticArray` works.
> StaticArray type fix

- package-lock.json
- package.json
Our upgrade to v7 used to be blocked because we were using `files` in an exotic way they did no longer support. Now, we are not using that anymore, yet they removed caching somewhere along the road to v8, making stuff really slow. LKGR for our purposes is v6.
> Downgrade ts-node to v6 again

- .github/workflows/ci.yml
- .github/workflows/publish.yml
I still have no idea how this broke, so I patched `setup-node-nvm` to use a different setup approach, now always setting up the latest tagged version of nvm. Can also just use `@master` since we are in control of it.
> Fix nvm CI issues

- src/compiler.ts
Issue:  https://github.com/AssemblyScript/assemblyscript/issues/1181
When we were resolving a function from an identifier, we would call the `resolveFunction` method without any typeArguments. This guarantees an assertion failure in the event that the function requires type parameters.
This PR adds a check in the `compileIdentifierExpression` call just before it tries to resolve the function which will print out a nicer error message.
```typescript
function doit<T,X,O,N>(x: T): T {
return x
}
export function test(x: i32): void {
let x = doit<String("hey!");
}
```
Results in:
```
ERROR: AssertionError: assertion failed
```
Results in:
```typescript
ERROR TS2554: Expected 4 arguments, but got 0.
let x = doit<String("hey!");
~~~~
in main.ts(9,11)
ERROR AS225: Expression cannot be represented …
```
> Added helpful error when missing type parameters

- .github/workflows/ci.yml
Turned out that the author check in our CI action can use different author email addresses for the PR and the merge, so this PR excludes the author check from merges as well.
> Check precondition in CI on PRs only

- tests/compiler/std/string-casemapping.optimized.wat
- tests/compiler/std/string-casemapping.ts
- tests/compiler/std/string-casemapping.untouched.wat
CI is currently broken due to https://github.com/AssemblyScript/assemblyscript/issues/1195, so this PR disables the respective asserts until we know more.
> Temporarily disable casemapping checks against node/v8

- src/compiler.ts
- src/program.ts
- tests/compiler/features/not-supported.json
- tests/compiler/features/not-supported.ts
This PR should fix https://github.com/AssemblyScript/assemblyscript/issues/1162 in that `v128` and `anyref` will always be present, even if the respective feature is not enabled, so these can be used conditionally. Chances are that I am missing diagnostics somewhere, but general strategy is to check on use of a storage type
* Declaring a local of that type
* Declaring a global of that type
* Reading or writing a field of that type
* Compiling a function with a respective this, parameter or return type
* Instantiating a class with a field of that type
and when a new value of the type is created by one of the respective builtins, which should also cover all sorts of inference if no type is annotated on a storage type. That should give us the minimum amount of diagnostics, instead of …
> Always register non-MVP types and check on actual use

- src/program.ts
Issue: https://github.com/AssemblyScript/assemblyscript/issues/1176
When using the documented `--use abort=`abort would be set to an empty string, which resulted in the call to global aliases returning ''. Then since blank strings are falsey, this assertion would fail.
I've changed the assertion to assert that the name is a string, which catches the case that the alias is missing but does not fail in the case of an empty string
examples:
If the name isn't found in the aliases table:
```typescript
//let alias = unchecked(_keys[i]);
let alias = "not the right key"
let name = globalAliases.get(alias);
assert(isString(name));
```
We get: `ERROR: AssertionError: assertion failed` as expected.
In the case where you specify an abort that does not match any export:
`ERROR: no such global element: …
> Change assert to allow blank strings

- src/compiler.ts
- tests/compiler/std/object-literal-unmanaged.json
- tests/compiler/std/object-literal-unmanaged.optimized.wat
- tests/compiler/std/object-literal-unmanaged.ts
- tests/compiler/std/object-literal-unmanaged.untouched.wat
As reported in https://github.com/AssemblyScript/assemblyscript/issues/1183 instantiating an unmanaged class from an object literal, like in
```ts
@unmanaged
class Foo {
a: i32;
}
var foo: Foo = { a: 1 };
```
results in unexpected behavior. Wasn't able to reproduce the issue Wasm Studio produces on current master, but it was indeed trying to retain/release unmanaged memory, which might have been the cause and should be fixed now, along a proper diagnostic when attempting this in `--noUnsafe` contexts. @jtenner Does this fix the original problem?
> Handle instantiation of unmanaged class via object literal

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- README.md
Have made what I hope are a few improvements to the underlying action, and this PR uses them.
> Fix CI once again

- cli/util/options.js
When I was porting this module to TypeScript for a personal project, (and referencing it via the apache license,) I found this error.
> Fix option property access

- NOTICE
- cli/asc.js
- cli/util/mkdirp.js
- cli/util/utf8.js
I wanted to test #1216, but it turned out it was a bit more complicated. Thought I’d get my hands dirty rather than stretching this out any further. Hope you don’t mind, @MaxGraey.
Fixes #1215
> Respect absolute output paths

- src/ast.ts
- src/extra/ast.ts
- src/program.ts
This pull request is more of a question than a suggestion.
`EnumValueDeclaration` extends `VariableLikeDeclaration` and the `initializer` property remains unused. This change simply removes the `value` property and switches to use the `initializer` property, reducing memory usage for each `EnumValueDeclaration`.
Thoughts?
> Switch to initializer property

- src/extra/ast.ts
- src/index.ts
As discussed on slack. This software would be useful in some of our projects and for orm codegen.
For instance, `as-pect` has had lots of trouble with debugging sources when transforms are included, so this would enable developers to output transformed source code to inspect certain kinds of problems with transforms.
cc @willemneal because he definitely wanted this too.
Fixes #1212 as a first step.
Something more should be done.
> Export astbuilder

- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- tests/compiler/std/object-literal-omitted.json
- tests/compiler/std/object-literal-omitted.optimized.wat
- tests/compiler/std/object-literal-omitted.ts
- tests/compiler/std/object-literal-omitted.untouched.wat
- tests/compiler/std/object-literal.ts
closes #1226
This fixes the bug where omitted Object literals would just give random memory from the runtime. By introducing an error for class fields that cannot be omitted.
This Enhances Object literals, by allowing the [basic AS Types](https://docs.assemblyscript.org/basics/types). To be omitted, with default values of zero :smile: 
TODO: Either we add support for nullable types to default to null and/or add support for making a new instance of a class if the constructor has no parameters in this same PR. Or we can do that work in a seperate PR :smile: 
cc @dcodeIO @jtenner 
P.S. Yay! My first real AS Compiler PR :smile: :tada:
> Fix / Enhancement for Omitted Object Literals

- cli/asc.js
- src/module.ts
- tests/compiler/features/simd.optimized.wat
- tests/compiler/std/object-literal-omitted.optimized.wat
Started as an experiment, but worked out well, so here it is.
> Move optimization pipeline from JS to Wasm

- cli/asc.js
- src/glue/binaryen.js
- tests/decompiler.js
- webpack.config.js
While investigating build times on CI I noticed that asc builds are 4.5mb and include Binaryen. This must have gone wrong when `binaryen.ready` was introduced a while ago, leading to CI spending most of the time in webpack, so this PR fixes that (faster builds, ~830kb asc).
> Fix asc build

- src/compiler.ts
- tests/compiler/while.optimized.wat
- tests/compiler/while.ts
- tests/compiler/while.untouched.wat
fixes https://github.com/AssemblyScript/assemblyscript/issues/1239
> Fix invalid flow assumption in 'if' compilation

- std/assembly/bindings/wasi_snapshot_preview1.ts
- tests/compiler/wasi/snapshot_preview1.ts
- tests/compiler/wasi/snapshot_preview1.untouched.wat
fixes https://github.com/AssemblyScript/assemblyscript/issues/1116 if it turns out that the new assumptions made there are correct. Also see the linked WASI issue.
> Fix WASI struct sizes

- src/module.ts
- tests/compiler/converge.json
- tests/compiler/converge.optimized.wat
- tests/compiler/converge.ts
- tests/compiler/converge.untouched.wat
fixes https://github.com/AssemblyScript/assemblyscript/issues/1248
During converge we call `Module#toBinary` with no arguments since the source map is irrelevant to determine just binary size, with the implicit `undefined` resulting in the issue in portable code.
> Fix converge option

- src/parser.ts
- tests/compiler/reexport.optimized.wat
- tests/compiler/reexport.ts
- tests/compiler/reexport.untouched.wat
- tests/compiler/rereexport.optimized.wat
- tests/compiler/rereexport.ts
- tests/compiler/rereexport.untouched.wat
- tests/compiler/wildcard-export.optimized.wat
- tests/compiler/wildcard-export.untouched.wat
Fixes the parser bailing on `default` in
```ts
export { default as something } from "./something";
```
due to identifier handling.
Related: https://github.com/AssemblyScript/assemblyscript/issues/98
> Fix identifier handling on export { default as ... }

- bin/asinit
- cli/asc.d.ts
- cli/asc.js
- cli/asc.json
- lib/parse/package.json
- lib/webpack/index.js
- package.json
- tests/allocators/buddy/package.json
- tests/allocators/rt-full/package.json
- tests/allocators/rt-stub/package.json
- tests/compiler.js
- tests/compiler/features/simd.ts
- tests/compiler/std/simd.ts
- tests/packages/package.json
- tests/packages/packages/g/test.js
- tests/runtime/package.json
Validation isn't that costly, and always good to do, and typically added to the command line to be sure. Hence this PR changes the `--validate` option to be enabled by default, making it opt-out with `--noValidate`.
> Validate modules by default

- cli/asc.json
- src/compiler.ts
- src/definitions.ts
- src/flow.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/builtins.optimized.wat
- tests/compiler/builtins.untouched.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/resolve-propertyaccess.optimized.wat
- tests/compiler/resolve-propertyaccess.ts
- tests/compiler/resolve-propertyaccess.untouched.wat
- tests/compiler/resolve-ternary.untouched.wat
This PR fixes https://github.com/AssemblyScript/assemblyscript/issues/1252 by refactoring static property prototypes to have a singleton instance. Previously, the compiler would instead resolve the respective getter/setter, skipping over the static prototype, while it now behaves more like with functions. Note that this still does not apply to instance properties, since properties can never be generic anyway so these are resolved together with the class, which then doesn't contain property prototypes anymore.
While on it, I also made compilation of `this` arguments use the correct type, which is either the implicit or explicit `this` type of a function or getter/setter, or the class type for fields. Noticed that this was still TODO for properties, but then also implemented it for …
> Refactor static properties / use correct this arguments

- src/compiler.ts
- tests/compiler/assert-nonnull.untouched.wat
- tests/compiler/class.untouched.wat
- tests/compiler/infer-array.untouched.wat
- tests/compiler/resolve-elementaccess.untouched.wat
- tests/compiler/retain-release-sanity.untouched.wat
- tests/compiler/retain-release.untouched.wat
- tests/compiler/std/array-access.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/arraybuffer.optimized.wat
- tests/compiler/std/arraybuffer.untouched.wat
- tests/compiler/std/dataview.optimized.wat
- tests/compiler/std/dataview.untouched.wat
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/set.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/symbol.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
- tests/compiler/throw.json
- tests/compiler/throw.optimized.wat
- tests/compiler/throw.ts
- tests/compiler/throw.untouched.wat
Fixes flows not becoming properly terminated after `throw`ing, leading to invalid `__release`s down the road. Related: https://github.com/AssemblyScript/assemblyscript/issues/1261
> Fix incorrect flow state after throwing

- src/compiler.ts
- tests/compiler/logical.json
- tests/compiler/logical.optimized.wat
- tests/compiler/logical.ts
- tests/compiler/logical.untouched.wat
An attempt to fix https://github.com/AssemblyScript/assemblyscript/issues/1136 by refining the existing special case for contextual `bool` on logical `LHS && RHS` and `LHS || RHS`.
For a bit of background: We can't model this exactly like JS because it would involve a union `typeof(LHS) | typeof(RHS)`, so the compiler currently compiles LHS with the outer contextual type allowing it to deviate and RHS with LHS's type as the contextual type *forcing an implicit conversion* to get a single AOT-compatible type.
The important difference this PR introduces is that the compiler no longer attempts to implicitly convert the RHS expression to the LHS type if the outer contextual type is `bool` or `void`, instead allowing both LHS and RHS to have different types, which is fine since subsequent …
> Rework logical and/or type rules on contextual bool

- package-lock.json
- package.json
- src/builtins.ts
- src/glue/binaryen.d.ts
- src/module.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
Removes API tracing definitions, adds `copyExpression` and `f32x4/f64x2.pmin/pmax`.
> Update Binaryen and other dependencies

- cli/asc.d.ts
- cli/asc.js
- cli/asc.json
Renames the `--asmjsFile` (alias `-a`) command line option to `--jsFile` (alias `-j`), matching what has been done on the Binaryen side, i.e. the respective tool is now also named `wasm2js` and the generated file isn't actually valid asm.js anymore.
> Rename asmjsFile to jsFile

- cli/asc.d.ts
- cli/asc.js
- cli/asc.json
- src/index.ts
These functions were helpful for debugging, but it appears that set of problems are stable. From a previous conversation with @dcodeIO, he was thinking about removing these functions, and I figure it would be a good idea to get the ball rolling on this breaking change.
Questions:
1. Is anyone actually using this feature?
2. Am I forgetting something that should also be removed?
3. Should we leave buildrtti in so that downstream developers can still use it anyway?
> Remove printrtti and buildrtti

- cli/util/options.d.ts
- cli/util/options.js
This will be useful in the following ways:
1. Aspect and other projects that bootstrap the compiler can reuse the cli parser and reduce code size
2. We can reuse this for when I get back around to asconfig
3. Maybe other uses
This is a very small change too. Should `provided` be a `Set<string>`, or `string[]`?
> Add provided set to cli parser

- package-lock.json
- package.json
* Added a `seed` import (along `abort` and `trace`) for seeding the random number generator
* Arrays no longer inherit from ArrayBufferView, but are now distinct
* The loader API now more closely aligns with the WebAssembly API
* Various compiler API changes (i.e. decoupled the parser from the program)
* Classes initialized from object literals can no longer define a constructor
* Moved examples from the main repo to their [own repo](https://github.com/AssemblyScript/examples)
* Modules now become validated by default (disable with `--noValidate`, `--validate` is gone)
* Reworked memory options (added `--noExportMemory`, `--initialMemory`, `--maximumMemory`, with `--sharedMemory` now being a boolean flag)
* Renamed the `--asmjsFile` command line option to `--jsFile` (alias: `-j`)
* …
> Slice version 0.10.0

- std/assembly/index.d.ts
Hello!
So when I was [upgrading as-bind](https://github.com/torch2424/as-bind/pull/34), I noticed that AssemblyScript wasn't working with the Typescript compiler, due to a bad definition the Typescript compiler didn't like:
So I went ahead and just modified my `node_modules` directly. I tried the type: `valueof<T extends unknown[]>[]`, but that didn't work. I *think* this new type in this PR correctly represents what we want, and it works (ignore the red test, was just trying to test things really quick):
cc @dcodeIO @MaxGraey 
We may want to push a minor out to npm for this? Since this will require people to modify their node modules for the `tsc` compatibility.
> Changed the Array.flat() definition to work with Typescript Compiler

- lib/loader/README.md
A while back it has been suggested to make the loader helpers check for zeroes implicitly, raising an error. While that seems good to do initially, it leads to a situation where users will check for zeroes manually to avoid throwing, and the helper will check for zero once again in case it has to throw. To avoid redundant checks like these, this PR instead documents the behavior more clearly, expecting users to check for zeroes where necessary. In the worst case there'll be one check in user code this way, while in the best case there's no check at all.
See: https://github.com/AssemblyScript/assemblyscript/pull/381
> Document null pointer behavior of the loader helpers

- .github/workflows/test.yml
- package-lock.json
- src/ast.ts
- src/builtins.ts
- src/compiler.ts
- src/definitions.ts
- src/extra/ast.ts
- src/flow.ts
- src/module.ts
- src/parser.ts
- src/program.ts
- src/resolver.ts
- src/tokenizer.ts
- src/tsconfig.json
- std/assembly/map.ts
- std/assembly/set.ts
- std/assembly/shared/typeinfo.ts
- tests/compiler/builtins.optimized.wat
- tests/compiler/builtins.untouched.wat
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/set.untouched.wat
- tests/compiler/std/symbol.optimized.wat
- tests/compiler/std/symbol.untouched.wat
- tslint.json
As the title says, this PR enables TypeScript's `--strict` mode (strict null checks, strict checking of function types, strict checking of property initialization in classes) in compiler sources by means of refactoring quite a bit of code. Also found a few potentially problematic places where `range`s were missing.
Helps https://github.com/AssemblyScript/assemblyscript/pull/1155 in particular in that the compiler sources don't need a heap of definitive assignment assertions anymore, where my expectation is that these will yield runtime checks ultimately, which we now avoid.
Technically this is a breaking change for internal compiler API users due to changed parameter orders and similar, but not for compiler users, so I'm not sure if we should make this a new major release just for that, …
> Refactor compiler sources to adhere to TS strict mode

- std/assembly/index.d.ts
> Add radix argument for standart definition file

- src/builtins.ts
- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/parser.ts
- src/resolver.ts
- tests/compiler.js
- tests/compiler/closure.json
- tests/compiler/wasi/trace.js
As a follow-up to https://github.com/AssemblyScript/assemblyscript/pull/1294 this also adds the respective missing feature to `Not implemented` diagnostics, looking like
```
AS100: Not implemented: ref.eq
AS100: Not implemented: Closures
AS100: Not implemented: Exceptions
```
while converting some of the diagnostics back to `assert`s, but only where hitting that code path would indicate a bug that must be fixed anyway and a diagnostic wouldn't be helpful, i.e. "Expression kind X cannot be looked up / resolved / compiled because someone forgot to implement it".
fixes #1294
> Reference feature in not implemented diagnostic

- src/compiler.ts
Extracting some no-op changes from my [Closures PR](https://github.com/AssemblyScript/assemblyscript/pull/1240/files) to make it easier to parse.
What's been extracted is just the change to have type information passed into retain/release in any scenario where the expression could refer to a function pointer.
While none of the below is actually present in this change, which does nothing, it explains what this change will be used for in the closures implementation.
With our current scheme of altering function references so that they can hold closures or normal function references, we need to know the type of a block in order to know how to retain or release it. 
- When the type is a function type, we check the MSB, and if it's set we retain/release a shifted value. If it isn't, we …
> Add unused type parameter to retain and release to prepare for closures

- src/program.ts
- tests/compiler/empty-use.json
- tests/compiler/empty-use.ts
Issue:  https://github.com/AssemblyScript/assemblyscript/issues/1296
With this PR, you can now specify an empty use statement to prevent an implementation from being injected with the following syntax: `--use Date=`. When attempting to use date, which is normally globally exported automatically, you will then instead get this error message:
```
ERROR TS2304: Cannot find name 'Date'.
Date.now();
~~~~
in main.ts(1,1)
ERROR: 1 compile error(s)
```
This is useful when you cannot support the module in question, which in the case of date would be due to the fact that the host will not import it.
> Empty use declarations now delete exported elements

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/parser.ts
- src/resolver.ts
- std/assembly/builtins.ts
- tests/compiler/basic-nullable.json
- tests/parser/continue-on-error.ts.fixture.ts
- tests/parser/regexp.ts.fixture.ts
Fixes https://github.com/AssemblyScript/assemblyscript/issues/558 by making
```ts
export function test1(x: void): void {}
export function test2(x: undefined): void {}
export function test3(x: null): void {}
export function test4(a: string | undefined): void {}
```
now diagnosing
```
ERROR TS1110: Type expected.
export function test1(x: void): void {}
~~~~
in input.ts(1,26)
```
```
ERROR TS2304: Cannot find name 'undefined'.
export function test2(x: undefined): void {}
~~~~~~~~~
in input.ts(3,26)
```
```
ERROR TS2304: Cannot find name 'null'.
export function test3(x: null): void {}
~~~~
in input.ts(5,26)
```
```
ERROR TS1005: 'null' expected.
export function test4(a: string | undefined): void {}
~~~~~~~~~
in input.ts(7,35)
```
with `test4` diagnosed early on parser level.
> Print better errors for unusual void, null and undefined types

- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- tests/compiler/export-generic.json
- tests/compiler/export-generic.ts
A revised implementation of https://github.com/AssemblyScript/assemblyscript/pull/981 that doesn't skip compilation, since it might be intended by the user to export a specific concrete instance when being aware of the limitations. Warns if an exported generic function or class has no instances, since that's most likely unintended.
Fixes https://github.com/AssemblyScript/assemblyscript/issues/570
Fixes https://github.com/AssemblyScript/assemblyscript/pull/981
> Warn on unused generic exports

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
As a follow-up to the respective agenda item at our [12th Working Group meeting](https://github.com/AssemblyScript/working-group/issues/36#issuecomment-631721787), this PR adds relatively light issue and PR templates to the repository and clarifies a few points within the contributing guidelines. Here's the diff:
---
Submitting Pull Requests
------------------------
[...]
* Consider **creating an issue to discuss first** and **later link to it from the PR** if this is not a trivial fix.
[...]
Please note that if a pull request is rather complicated, i.e. touches lots of internals, or became stale, it is not uncommon that a core contributor performs the final integration to get it done in good conscience while naming you as a co-author.
Thank you!
---
Doesn't go overboard with the …
> Add issue and PR templates, clarify guidelines

- NOTICE
- std/portable/index.d.ts
- std/portable/index.js
> Implement portable variants of TypedArray.wrap

- cli/asc.js
- src/index.ts
- src/parser.ts
- tests/packages/packages/g/test.js
This PR fixes https://github.com/AssemblyScript/assemblyscript/issues/1282 by adding the paths searched to the error message when an imported file cannot be found, for example when trying to import a file by erroneously specifying a file extension, looking like:
```
ERROR: Import 'tests/compiler/404.ts' not found.
No such file 'path\to\tests\compiler\404.ts.ts'
No such file 'path\to\tests\compiler\404.ts\index.ts'
No such file 'path\to\tests\compiler\404.ts.d.ts'
```
Doesn't implement a `.ts` specific error message because that might be intended, but the problem should be clear from the paths searched. cc @torch2424
> Improve error message if an import cannot be found

- NOTICE
- std/assembly/index.d.ts
- std/assembly/shared/target.ts
- std/portable/index.d.ts
From what I can tell, it's 0 for WASM32, not JS.
> Fixed compiler constant hint in typescript typedefs

- src/resolver.ts
- tests/compiler/function-expression.optimized.wat
- tests/compiler/function-expression.ts
- tests/compiler/function-expression.untouched.wat
This PR fixes https://github.com/AssemblyScript/assemblyscript/issues/1289 by resolving variable types to their respective function targets (if there is one, otherwise errors) in `resolveCallExpression`. Works because all the compiler is interested in on `CallExpression` is a callable, not the element, and the old behavior can be achieved by unwrapping and resolving `callExpression.expression` instead if that becomes necessary (currently isn't).
> Implicitly resolve to callables when resolving call expressions

- .eslintrc.js
- bin/asinit
An alternative to fix https://github.com/AssemblyScript/assemblyscript/pull/1164 by checking if the compiler is in fact a normal dependency, and if so using node resolution in the generated tsconfig.json.
> Use node resolution in asinit-generated tsconfigs if possible

- src/module.ts
- tests/compiler/extends-baseaggregate.optimized.wat
- tests/compiler/issues/1095.optimized.wat
- tests/compiler/logical.optimized.wat
- tests/compiler/managed-cast.optimized.wat
- tests/compiler/object-literal.optimized.wat
- tests/compiler/rc/optimize.optimized.wat
- tests/compiler/resolve-ternary.optimized.wat
- tests/compiler/retain-release-sanity.optimized.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/arraybuffer.optimized.wat
- tests/compiler/std/dataview.optimized.wat
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/string-casemapping.optimized.wat
- tests/compiler/std/string-encoding.optimized.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/typedarray.optimized.wat
Disables the problematic half of ARC optimizations for now due to https://github.com/AssemblyScript/assemblyscript/issues/1288. Keeping my eyes open for a proper fix.
> Disable aggressive ARC optimizations

- src/common.ts
- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/flow.ts
- src/program.ts
- tests/compiler/variable-access-in-initializer.json
- tests/compiler/variable-access-in-initializer.ts
An alternative to fix https://github.com/AssemblyScript/assemblyscript/pull/1205 by remembering globals that failed to compile so we properly get a `false` upon subsequent `compileGlobal` invocations and don't run into `assert`s in the first place, as per my latest comment on the above PR.
@DuncanUszkay1: Can you confirm that this solves the issue as well?
If so, also fixes https://github.com/AssemblyScript/assemblyscript/issues/1165
Now also: fixes https://github.com/AssemblyScript/assemblyscript/issues/1186, fixes https://github.com/AssemblyScript/assemblyscript/pull/1190
> Remember failed globals so we don't hit assertions

- NOTICE
- bin/asinit
- Fixed default package template's exports.
> Fixed missing exports in asinit

- README.md
The SVGs on the README now have a `viewBox` instead of a `width` and a `height`, hence these scale to 100% width by default. This PR sets them to 720.
> Fix README image widths

- .eslintrc.js
- std/assembly/index.d.ts
- std/assembly/shared/target.ts
- std/portable/index.d.ts
- std/portable/index.js
- tests/compiler/asc-constants.untouched.wat
- tests/compiler/wasi/snapshot_preview1.untouched.wat
> Make JS Target value 0 in enum and ASC_VERSION

- lib/loader/index.js
- use string templates
- speedup `getStringImpl` by switching from collecting array parts to direct string concatenations
> modernize loader

- README.md
> chore: enlarge doc links in README

- package.json
Turns out the switch to semantic releases with `0.0.0` in the package.json broke the SDK's dist files, so this reorders the SDK build step to happen after the version has been written during publish.
> fix: Fix version string in SDK dist files

- std/assembly/util/number.ts
- std/assembly/util/string.ts
- std/assembly/wasi/index.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
- tests/compiler/wasi/trace.optimized.wat
- tests/compiler/wasi/trace.untouched.wat
For better consistency I wanted to do this a long time ago.
Not sure is it breaking changing or not due to this methods usually used internally.
> refactor: Rename (dtoa|itoa)_stream to (dtoa|itoa)_buffered + simplify signature

- std/portable/index.js
> Fix fromCharCodes & fromCodePoints polyfills

- src/module.ts
See [this](https://github.com/AssemblyScript/assemblyscript/pull/1341#discussion_r440895843) comment for details
> Improve and fix utf-8 encoding / decoding for module

- src/glue/binaryen.js
- src/glue/js/collections.js
- src/glue/js/float.js
- src/glue/js/i64.js
- src/glue/wasm/collections.ts
- src/glue/wasm/float.ts
- src/glue/wasm/i64.ts
- src/module.ts
Also fix some UTF8 decoding / encoding issues between AS and Binaryen
> refactor(compiler): Modernize & refactoring some internal parts

- cli/asc.json
- cli/util/options.d.ts
- cli/util/options.js
- tests/cli/options.js
This is an attempt to solve the reconciliation problems encountered during https://github.com/AssemblyScript/assemblyscript/pull/1238 by extending the existing options parser with a backtracking merge algorithm.
With this, we'd essentially start by parsing command line arguments, obtaining an initial set of options, then merge the project's `asconfig.json` if applicable and continue by merging parent project `asconfig.json`s until we reach the end. Once done, we can add option defaults that we so far omitted.
The options `enable` and `disable` now have an additional `mutuallyExclusive` key indicating that whatever is newer in the respective other equalizes what's older. Does not affect the same level, but only merging a previous level.
There is a basic test in `tests/cli/options.js`, …
> feat(asc): Add options merge algorithm for use by asconfig

- src/compiler.ts
- tests/compiler/super-inline.json
- tests/compiler/super-inline.optimized.wat
- tests/compiler/super-inline.ts
- tests/compiler/super-inline.untouched.wat
Fixes https://github.com/AssemblyScript/assemblyscript/issues/1342, but does not try to reason about when we can inline nonetheless (can we safely inline any `super.xy()` call?). Now emits a warning instead of crashing.
> Fix assertion when trying to inline virtual (super) calls

- lib/sdk/index.js
- scripts/build-sdk.js
> fix: Change from "nightly" to "latest" AS version for sdk.js

- std/assembly/util/number.ts
- tests/compiler/number.untouched.wat
- tests/compiler/resolve-access.untouched.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/resolve-elementaccess.untouched.wat
- tests/compiler/resolve-function-expression.untouched.wat
- tests/compiler/resolve-propertyaccess.untouched.wat
- tests/compiler/resolve-ternary.untouched.wat
- tests/compiler/resolve-unary.untouched.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/string-casemapping.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/typedarray.untouched.wat
> feat(std): add isPowerOf2 helper

- .github/workflows/publish.yml
Turned out that after https://github.com/AssemblyScript/assemblyscript/pull/1358 the loader is always published, even if there isn't a new release. That led to current latest on npm being loader@0.0.0. This PR fixes this by indirectly checking if the main package has been published. Should also unbreak the latest tag at 0 UTC.
> Do not publish loader when there's no new release

- src/compiler.ts
- tests/compiler/field-initialization-errors.json
- tests/compiler/field-initialization-errors.ts
- tests/compiler/field-initialization.optimized.wat
- tests/compiler/field-initialization.ts
- tests/compiler/field-initialization.untouched.wat
As [reported](https://github.com/AssemblyScript/assemblyscript/pull/1349#issuecomment-652237081) on the original PR, strict field initialization did not account for inlined constructors that must be checked per inlined flow.
> Handle strict field initialization in inlined ctors

- src/compiler.ts
- src/program.ts
- tests/compiler/exports-lazy.json
- tests/compiler/exports-lazy.optimized.wat
- tests/compiler/exports-lazy.ts
- tests/compiler/exports-lazy.untouched.wat
Fixes a code generation problem with globals that are both a module export and declared `@lazy`, as reported by @MaxGraey on Discord, by extending the concept a bit to explicitly support annotating global and function exports as lazy (only yielding a module export if referenced from other code, and otherwise omitting).
> Support lazy global and function exports

- cli/asc.js
Reorders `asc`s various outputs so that `--jsFile` is always processed last, because conversion to JS can modify the original binary, previously leading to its artifacts being present in text format output (but not in binaries).
> Emit text format before emitting JS

- src/extra/ast.ts
- tests/parser/constructor.ts.fixture.ts
- tests/parser/function.ts.fixture.ts
- tests/parser/parameter-optional.ts
- tests/parser/parameter-optional.ts.fixture.ts
- tests/parser/parameter-order.ts.fixture.ts
- tests/parser/string-binding.ts.fixture.ts
Avoids adding a "?" to optional parameter if it has an initializer and adds a new parser test.
> Fix ASTBuilder for parameters

- src/diagnostics.ts
- src/parser.ts
- src/tokenizer.ts
> More parser & tokenizer refactorings

- cli/asc.js
relates to https://github.com/DuncanUszkay1/assemblyscript/pull/14
Please see the PR above for the context. But TL;DR I was working on closures, and the tests would hang when failing when validating the module. I think this return is meant to happen outside of the measure. 
With this fix, tests will not hang whenever a module cannot be validated correctly :smile: :+1: 
cc @dcodeIO @MaxGraey
> Fixed Incorrect Callback Return in CLI Module Validation

- cli/asc.js
Fixes a problem discovered in https://github.com/AssemblyScript/assemblyscript/pull/1238, where specifying `--outFile` would still emit text format to stdout, by reordering.
> Respect outFile when detecting no output in asc

- src/ast.ts
- src/compiler.ts
- src/parser.ts
As a follow-up to https://github.com/AssemblyScript/assemblyscript/pull/1319#discussion_r455396101, this PR adds an `OmittedExpression` AST node with a proper range for use in diagnostics. Also makes sure that arrays of `externref`s are never considered static, in turn yielding the expected diagnostic:
```
ERROR AS100: Not implemented: ref.null
var a: externref[] = [ , ];
^
```
(Note that the code above is still invalid for other reasons)
> Add a node representing an omitted expression

- .github/workflows/test.yml
- cli/asc.js
This is a relatively stupid workaround for https://github.com/AssemblyScript/assemblyscript/issues/1398 so we can get the editor on the website working again. Only works because baseDir in browsers is `.`. We'll still need a real fix but it's still unclear what's actually going on there.
> Preliminary path.relative workaround

- src/program.ts
- tests/compiler/class-implements.json
- tests/compiler/class-implements.optimized.wat
- tests/compiler/class-implements.ts
- tests/compiler/class-implements.untouched.wat
As reported in #1374 the compiler is hitting assertions when a class is both extending another class and implementing an interface. I do not recall why these assertions are there, and I can only assume that these are left-over from testing.
Fixes #1374
> Fix assertion when a class extends and implements

- cli/asc.js
- cli/shim/README.md
- cli/shim/fs.js
- cli/shim/path.js
- cli/shim/process.js
- cli/util/mkdirp.js
- package-lock.json
- package.json
- webpack.config.js
This started as an attempt to properly fix #1398, but turned out that path-browserify 1.0.1 still suffers from the problem, so I applied the preliminary fix in #1399 within the shim directly.
Anyhow, this now puts us in control of the specific shims being bundled, so if anything breaks in the future, we at least have the tools at hand to fix it directly in code instead of relying on external code to be updated.
> Bundle specific shims with asc instead of relying on defaults

- cli/asc.d.ts
- cli/asc.js
- cli/asc.json
- cli/util/options.d.ts
- cli/util/options.js
Fixes the merge order part of https://github.com/AssemblyScript/assemblyscript/pull/1404 by updating to the originally intended order
1. CLI arguments (without defaults)
2. ASConfig target
3. ASConfig options
4. Repeat 2. and 3. while ASConfig extends
5. Add defaults
while moving the defaults for `target` and `config` to asc itself because we need these early. Previously, the initial invocation of `parse` missed to omit populating defaults, and #1404 also seems to populate these too early.
> Fix asconfig merge order

- src/compiler.ts
- src/util/index.ts
- src/util/vector.ts
- tests/compiler/features/simd.ts
- tests/compiler/features/simd.untouched.wat
This is a suggestion to fix https://github.com/AssemblyScript/assemblyscript/issues/1409 by keeping precompute intact but disabling inlining of `const` `v128`s. In the given case
```ts
const one = i32x4.splat(1);
```
will precompute the value to a `v128.const` (initializer might be arbitrarily complex), but will not attempt to inline an eventual constant in subsequent code and instead leave the decision to do so to Binaryen.
> Fix assertion when declaring a const v128

- package.json
Fixes #1379 by forcing a rebuild of dist files after updating the release version during semantic release. Is a little dangerous because we are technically publishing something that hasn't been tested in this exact form, but since there's no better alternative and only the version string should differ in practice it's probably fine.
> Rebuild with known version before publishing

- std/assembly/util/memory.ts
- tests/compiler/extends-baseaggregate.untouched.wat
- tests/compiler/infer-array.untouched.wat
- tests/compiler/number.untouched.wat
- tests/compiler/object-literal.untouched.wat
- tests/compiler/resolve-access.untouched.wat
- tests/compiler/resolve-binary.untouched.wat
- tests/compiler/resolve-elementaccess.untouched.wat
- tests/compiler/resolve-ternary.untouched.wat
- tests/compiler/retain-release-sanity.untouched.wat
- tests/compiler/rt/finalize.untouched.wat
- tests/compiler/rt/stub-realloc.untouched.wat
- tests/compiler/std/array-literal.untouched.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/arraybuffer.untouched.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/pointer.untouched.wat
- tests/compiler/std/set.untouched.wat
- tests/compiler/std/static-array.untouched.wat
- tests/compiler/std/staticarray.untouched.wat
- tests/compiler/std/string-casemapping.untouched.wat
- tests/compiler/std/string-encoding.untouched.wat
- tests/compiler/std/string.untouched.wat
- tests/compiler/std/symbol.untouched.wat
- tests/compiler/std/typedarray.untouched.wat
- tests/compiler/wasi/trace.untouched.wat
Ref: https://git.musl-libc.org/cgit/musl/tree/src/string/memmove.c
> Simplify check condition for memcpy path in memmove

- std/assembly/math.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.untouched.wat
- tests/compiler/wasi/seed.optimized.wat
- tests/compiler/wasi/seed.untouched.wat
sync with [musl's commit](https://git.musl-libc.org/cgit/musl/commit/?id=d20558148d8a2c52229b02668627697e83ca3840)
> The final rounding operation should be done with the correct sign
otherwise huge results may incorrectly get rounded to or away from
infinity in upward or downward rounding modes.
> This affected sinh and sinhf which set the sign on the result after
a potentially overflowing mul. There may be other non-nearest rounding
issues, but this was a known long standing issue with large ulp error
(depending on how ulp is defined near infinity).
> The fix should have no effect on sinh and sinhf performance but may
have a tiny effect on cosh and coshf.
In theory it shouldn't affect to us due to Wasm guarantee always have round-to-nearest mode. But It's cost nothing in term of …
> refactor: sinh overflows in non-nearest rounding

- NOTICE
- bin/asinit
This diff improves the user experience when using other package managers than npm, by referencing the right commands. This is important, because as I described in https://github.com/AssemblyScript/assemblyscript/issues/495#issuecomment-675142864 the package manager install artifacts aren't strictly compatible, especially in the more modern setups.
Fixes https://github.com/AssemblyScript/assemblyscript/issues/495
> Infer the right package manager per the environment

- .eslintrc.js
- cli/asc.js
- cli/util/options.js
- webpack.config.js
> Use dynamic require in asc.js without eval

- src/ast.ts
- src/program.ts
> Fix source map column numbers being off by one

- std/assembly/math.ts
- std/portable/index.js
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.ts
- tests/compiler/std/math.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
I don't think we should ignore sign for NaNs due to signed `-NaN` is actually valid and canonical.
> Simplify Math.signbit. Don't ignore sign bit for NaNs

- lib/loader/index.js
- lib/loader/tests/index.js
Fix #1470
Since node.js `8.x` (LTS) have `util.TextDecoder`
Since node.js `11` (LTS) have `global.TextDecoder`
> feat(loader): use TextDecoder for large strings

- package-lock.json
- package.json
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/typedarray.optimized.wat
This binaryen version contain [fix](https://github.com/WebAssembly/binaryen/pull/3197) issue introduced in current version
cc @dcodeIO 
plz merge it asap
> fix: Update binaryen with some fixes

- src/builtins.ts
- tests/compiler/builtins.optimized.wat
- tests/compiler/builtins.ts
- tests/compiler/builtins.untouched.wat
> fix(compiler): Implement proper left / right cyclic builtin rotation for small integers

- src/builtins.ts
- src/compiler.ts
In https://github.com/AssemblyScript/assemblyscript/pull/1484 it became apparent that we can share the code the compiler uses when compiling binary expressions, including taking care of SMI wrapping, during implementation of https://github.com/AssemblyScript/assemblyscript/issues/1310, so this refactors just making the IR out of `compileBinaryExpression`.
> Refactor binary expression compilation to be reusable in builtins

- src/builtins.ts
- tests/compiler/builtins.untouched.wat
> fix: polyfills for small types in builtin_rotl/rotr should use temp variables

- src/builtins.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
- tests/compiler/builtins.optimized.wat
- tests/compiler/builtins.ts
- tests/compiler/builtins.untouched.wat
Initially wanted to add more built-ins, but found that various definitions were missing, so ended up cleaning these up instead. Also adds `div<T>` respectively i32/i64/f32/f64.div(_s/u).
> Clean up inline-asm definitions, add i32/i64/f32/f64.div(_s/u)

- src/definitions.ts
changes:
- align assignments
- `BigInt` -> `bigint`
- `type bool = any` -> `type bool = boolean | number`
> Improve generated type defininitions for ASModule

- src/compiler.ts
- tests/compiler/abi.untouched.wat
- tests/compiler/retain-i32.ts
- tests/compiler/retain-i32.untouched.wat
- tests/compiler/std/dataview.untouched.wat
- tests/compiler/std/polyfills.untouched.wat
Similar to #1494 we should wrap RHS shifting value by maximum size of type in bits.
For booleans we just return `leftExpr` due to `leftExpr <<>> rightExpr & (1 - 1)` -> `leftExpr <<>> 0` -> `leftExpr`
> fix(compiler): wrap RHS shifting value by maximum size of type in bits for small integers

- lib/rtrace/README.md
- lib/rtrace/index.d.ts
- lib/rtrace/index.js
- lib/rtrace/package.json
- lib/rtrace/umd/index.d.ts
- lib/rtrace/umd/index.js
- lib/rtrace/umd/package.json
- package.json
- tests/bootstrap/index.ts
- tests/compiler.js
Does what https://github.com/AssemblyScript/assemblyscript/pull/1513 did for the loader for RTrace as well.
> Make Rtrace ESM by default, with UMD fallback

- std/assembly/number.ts
Suppresses a `Conversion from type 'usize' to 'u32' will require an explicit cast` warning when calling `someUsize.toString()` due to a missing explicit cast.
> Use explicit cast in Usize/Isize#toString

- package-lock.json
- package.json
- tests/compiler/number.optimized.wat
- tests/compiler/resolve-binary.optimized.wat
- tests/compiler/resolve-ternary.optimized.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/mod.optimized.wat
- tests/compiler/std/typedarray.optimized.wat
> Update to latest binaryen

- std/assembly/math.ts
- tests/compiler/binary.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.untouched.wat
- tests/compiler/std/mod.optimized.wat
- tests/compiler/std/mod.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
> Slightly optimize Math.mod

- std/assembly/index.d.ts
- std/assembly/memory.ts
Updates a few comments to the same wording as is now used on the documentation.
> Align comments of the new heap functions with docs

- tests/compiler/std/string-casemapping.optimized.wat
- tests/compiler/std/string-casemapping.ts
- tests/compiler/std/string-casemapping.untouched.wat
> Fix string casemapping test

- package.json
With the fallback, legacy cases like
```ts
import asc from "assemblyscript/cli/asc";
import options from "assemblyscript/cli/util/options";
import distAsc from "assemblyscript/dist/asc";
```
including others we haven't though of yet are covered by always resolving `./* -> ./*.js`. Fixes https://github.com/AssemblyScript/assemblyscript/pull/1522
At some point we'll most likely want to break this, either to pull packages out of the main packages or make nicer entry points like just `/loader`, but this gives us sufficient backwards compatibility (on node >= 15, need to check 14) for now so is good to do :)
**Edit:** According to the node 14 docs, the fallback should work there as well.
> Add package exports fallback for the CLI, dist files, etc.

- lib/rtrace/index.d.ts
Hello! I was trying to extend the RTrace class and found out that some of the types were incomplete and missing. The pull request currently contains everything as-pect would need to properly extend the class. Is there anything that can be added which would be helpful to others?
I am also very open to suggestions on wording the comments.
> RTrace TypeScript Types Update

- cli/asc.js
- src/glue/binaryen.js
- src/module.ts
this add ability print `.wast` (superset text format) as well. 
@dcodeIO Sometimes this preferable. Especially useful for producing binaryen's test cases.
This shouldn't break any backward compatibility.
> Support .wast extention for --textFile

- cli/asc.js
Fixes one use of `{ encoding: "utf8" }` on `Stream#write`, which was incorrect (not an option argument, just encoding), and removes unnecessary encoding arguments where the default is already `"utf8"`, i.e. on `fs.writeFileSync` with a string argument.
> fix: Fix invalid and remove unnecessary string encoding arguments in asc

- lib/rtrace/index.d.ts
- lib/rtrace/index.js
- lib/rtrace/umd/index.js
> Export block and object layout constants from Rtrace

- std/assembly/map.ts
- std/assembly/set.ts
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/set.untouched.wat
- tests/compiler/std/symbol.optimized.wat
- tests/compiler/std/symbol.untouched.wat
> [std] Slightly improve Map/Set by caching some props

- src/util/binary.ts
Another bug discovered in #1559 affecting static memory segment creation when reading back `rtSize`s larger than 255, but only in the Wasm target, where indexed access on `Uint8Array` yields actual `u8` values.
> fix: Fix binary util discarding bits when compiling to Wasm

- src/compiler.ts
- tests/compiler/class-implements.optimized.wat
- tests/compiler/class-implements.untouched.wat
- tests/compiler/extends-recursive.optimized.wat
- tests/compiler/extends-recursive.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
Fixes an oddity with automatically generated constructors, where if the class has a base class the generated ctor would not be exported along an `export class Something`.
> Unify ctor generation with and without base ctor

- src/module.ts
Fixes an OOB array access affecting the Wasm but not the JS target, discovered in #1559.
> Fix OOB array access in runPasses

- src/compiler.ts
- tests/compiler/exports.ts
Fixes an unexpected assertion when an interface is exported (to the host) due to interfaces not yet being handled in `ensureModuleExport` respectively `compileElement`. Fixes #1599
> Fix assertion on exported interfaces

- NOTICE
- src/definitions.ts
Fixes https://github.com/AssemblyScript/assemblyscript/issues/1617
> issue-1617 Adding wrap definition.

- src/definitions.ts
This PR complements [this issue](https://github.com/AssemblyScript/website/issues/41). I've realized that part of the problem why I found that feature so late is because the TS definition doesn't come with valueOf() override that returns `usize` pointer instead of an `Object`.
> Adding valueOf override to generated TS class definitions.

- webpack.config.js
Should fix editor breakage on the website. The issue was introduced by `asc` now needing the loader and rtrace for Wasm builds of the compiler, with the configuration to make these externals causing the issue apparently.
> Bundle loader and rtrace with asc

- std/assembly/dataview.ts
- std/assembly/index.d.ts
> switch to bool in DataView

- cli/asc.js
As discovered in https://github.com/AssemblyScript/examples/pull/11, `asc` now always wraps the module in a Binaryen.js module instance, so the correct method to call here is `emitAsmjs`, not `toAsmjs`.
> Fix emitting ASMJS

- cli/asc.json
- src/compiler.ts
- tests/compiler/features/nontrapping-f2i.json
- tests/compiler/features/nontrapping-f2i.optimized.wat
- tests/compiler/features/nontrapping-f2i.ts
- tests/compiler/features/nontrapping-f2i.untouched.wat
- tests/features.json
This PR implements the meanwhile finished [Non-trapping float-to-int Conversion Proposal](https://github.com/WebAssembly/nontrapping-float-to-int-conversions), suggesting to make it the default behavior over the respective trapping instructions. Reasoning is that trapping can lead to all sorts of breakage with the current runtime, so relying on that would be dangerous.
Keeps the feature behind a flag for now because Safari doesn't yet support it. A follow-up PR could be to explicitly opt-in to trapping operations if so desired, by using a new `checked(...)` builtin.
> Implement nontrapping-f2i proposal

- src/compiler.ts
- tests/compiler/new.optimized.wat
- tests/compiler/new.ts
- tests/compiler/new.untouched.wat
The code responsible to enable `arr: Array<i32> = new Array()` didn't check that both prototypes match before attempting to substitute type arguments, ultimately hitting an assertion that ensures that there's no unexpected "type argument count mismatch".
fixes https://github.com/AssemblyScript/assemblyscript/issues/1622
> Substitute type arguments in 'new' only if prototypes match

- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
When a static element that has no runtime representation in AS was accessed, the compiler only had an assertion assuming that would never happen, but should print a diagnostic instead because it can happen.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1654
> Emit a diagnostic when an expression only refers to a static element

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/parser.ts
- src/tokenizer.ts
- tests/parser/literals.ts
- tests/parser/literals.ts.fixture.ts
Rejects invalid code like `1u8`, just like TS would, by complaining about an identifier or keyword immediately following a numeric literal, during parsing.
Does not yet account for a BigInt literal's `n` postfix, since BigInts are not yet supported anyway. Other than that there may still be more to do here, like rejecting `1 2` or `a b` complaining about a missing `;` as TS would, but seems less urgent and is unrelated.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1637
> Reject identifier or keyword immediately following a numeric literal

- src/definitions.ts
Turns out that optional parameters were not yet supported when generating a .d.ts for a module, so this PR adds the `?`.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1644
> Support optional parameters in d.ts generation

- src/compiler.ts
- tests/compiler/function-call.optimized.wat
- tests/compiler/function-call.untouched.wat
- tests/compiler/function-expression.optimized.wat
- tests/compiler/function-expression.ts
- tests/compiler/function-expression.untouched.wat
Fixes the compiler not being able to refer back to named functions declared inside of functions, and makes sure that functions that are semantically anonymous (i.e. named but are part of an expression) do not conflict with named functions when initializing their program elements.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1652
> Properly handle semantically anonymous functions

- std/assembly/index.d.ts
As noted on the original issue, this doesn't make much of a difference but is technically OK in that `isArrayLike` checks for the presence of an index access overload. So we can as well just add it and resolve the original issue fwiw.
fixes https://github.com/AssemblyScript/assemblyscript/pull/1547
> Add index signature to ArrayLike

- src/builtins.ts
- src/compiler.ts
Fixes a couple places where types of function table indices and pointers to first class functions were confused. On that occasion, also fixes https://github.com/AssemblyScript/assemblyscript/pull/1459 which is related.
> Fix non-usize first-class function arguments to be usize

- bin/asc
- bin/asinit
- scripts/build-diagnostics.js
- src/diagnosticMessages.generated.ts
- std/assembly/bindings/wasi_snapshot_preview1.ts
- std/assembly/bindings/wasi_unstable.ts
- tests/cli/options.js
- tests/compiler/import.ts
Fixes https://github.com/AssemblyScript/assemblyscript/pull/1585, sans merge conflicts.
> Remove unused tslint comments / replace deprecated deepEqual

- src/compiler.ts
Calling `super` in the constructor of a non-derived class was hitting an assertion. Emit a diagnostic instead.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1677
> Emit a diagnostic when 'super' is called in ctor of a non-derived class

- lib/loader/index.js
- lib/loader/umd/index.js
This problem has been brought up in Discord recently iirc, and is one of these use-after-free kind of bugs (`__new` may step the GC) the docs warn about, yet I apparently forgot to account for in the loader itself.
> Fix premature collect of backing buffers in loader's __newArray

- lib/rtrace/index.d.ts
Adds the missing definitions for `oninit`, `oninterrupt`, `onyield`, `onstore` and `onload` and updates related descriptions.
> Update Rtrace definitions

- src/compiler.ts
Exports logic made the false assumption that a field that is tagged as `COMPILED` always has its implicit getters and setters compiled, which is not always the case.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1675
> Ensure exported field getters and setters are compiled

- src/tokenizer.ts
- tests/parser/literals.ts
- tests/parser/literals.ts.fixture.ts
Fixes https://github.com/AssemblyScript/assemblyscript/issues/1615
I think it makes sense to report a diagnostic until https://github.com/AssemblyScript/assemblyscript/issues/466 is implemented. We discovered this by accident as it was causing an unexpected behavior in one of our sdks.
> feat: Report a diagnostic when attempting to use a template literal

- NOTICE
- src/compiler.ts
- tests/compiler/issues/1699.optimized.wat
- tests/compiler/issues/1699.ts
- tests/compiler/issues/1699.untouched.wat
multiassignment causes compiler error later on code that has no errors
fix #1699
⯈
⯈
⯈
> fix misleading compile error on multi-assignment

- src/compiler.ts
- tests/compiler/features/reference-types.js
- tests/compiler/features/reference-types.ts
- tests/compiler/features/reference-types.untouched.wat
(This is my first PR digging into the compiler and I’m not 100% sure I did this right. Please point out anything you’d like changed.)
I was playing with reference types and notices that code like this behaves exactly inverted:
```ts
if(!someExternref) {
// This is executed when `someExternref` is *not* `null`
}
```
It seems like the logic in `makeIsTrueish` was just using `ref.is_null`, which would explain the inversion. This PR flips thats logic.
However, I couldn’t run the full tests as the tests still failed with `Feature 'gc' is not enabled.` despite setting `ASC_FEATURES="*"`. I guess that is the world of experimental features.
PTAL!
> Invert reference type null checks

- std/assembly/dataview.ts
- std/assembly/polyfills.ts
- tests/compiler/std/dataview.optimized.wat
- tests/compiler/std/dataview.untouched.wat
- tests/compiler/std/polyfills.untouched.wat
> Reduce monomophic versions of bswap in DataView

- .github/workflows/test.yml
- std/assembly/process.ts
- tests/compiler/std-wasi/crypto.optimized.wat
- tests/compiler/std-wasi/crypto.untouched.wat
- tests/compiler/std-wasi/process.optimized.wat
- tests/compiler/std-wasi/process.ts
- tests/compiler/std-wasi/process.untouched.wat
It is compared to a usize later and used as one later.
> fix: read stream signature

- tests/compiler/std/staticarray.optimized.wat
- tests/compiler/std/staticarray.ts
- tests/compiler/std/staticarray.untouched.wat
Adds the following missing tests for StaticArray:
- constructor
- fromArray
- concat (static)
- slice (static)
- concat (instance)
- includes
- indexOf
- join + toString
> tests: Add tests for StaticArray

- std/assembly/math.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.untouched.wat
- tests/compiler/wasi/seed.optimized.wat
- tests/compiler/wasi/seed.untouched.wat
Patch references [1](https://git.musl-libc.org/cgit/musl/commit/?id=964104f9f0e056cf58d9defa0b716d7756f040f6) and [2](https://git.musl-libc.org/cgit/musl/commit/?id=c4c38e6364323b6d83ba3428464e19987b981d7a)
> Backport fixes from musl's libc

- src/compiler.ts
When compilation of a property failed earlier, for example due to an unknown type, we were hitting an assertion upon access to the property.
fixes #1711
> Fix assertion when compiling a property errored earlier

- cli/asc.js
- cli/shim/process.js
Compiler crashes are annoying, and the stack trace produced is often not very useful. So this adds a crash handler to asc (currently on `initialize` and `compile`) that lets the user know that this should not happen and gives some advice how to debug the problem, or otherwise to let us know.
> Add a crash handler to asc

- cli/asc.json
The non-breaking bits of #1776, introducing the `-Ospeed` and `-Osize` shorthands.
> Add optimize shorthands for -Ospeed and -Osize

- cli/asc.d.ts
- cli/asc.js
see https://github.com/torch2424/as-bind/pull/75#issuecomment-812844458
cc @surma, @torch2424 Does this help?
> Allow specifying transforms via the compiler API

- src/compiler.ts
This patch reports a diagnostic when using a namespaced class (or any other construct)
that lacks a runtime representation as an expression.
Fixes https://github.com/AssemblyScript/assemblyscript/issues/1790
> fix: Fix usage of namespaced classes

- src/program.ts
Now, the error message is not format normally.
```
ERROR TS2300: Duplicate identifier '{0}'.
foo: number;
```
> fix: pass arg to Duplicate_identifier_0 for markVirtuals

- src/compiler.ts
Emits a diagnostic instead of hitting an assertion when trying to assign to an uncommon property like a method that is not a field.
fixes #1795
> Fix assertion when trying to assign to a method

- NOTICE
- std/assembly/bindings/Date.ts
- std/assembly/date.ts
- std/assembly/index.d.ts
- std/assembly/util/error.ts
- tests/compiler/std/date.json
- tests/compiler/std/date.optimized.wat
- tests/compiler/std/date.ts
- tests/compiler/std/date.untouched.wat
This PR adds
-  getters / setters for UTC dates (I don't plan to add any local-time related functionality)
- `fromString`, as a substitute for the `new Date("2345-11-04")` style constructor - I resisted the temptation to use [as-regex](https://github.com/ColinEberhardt/assemblyscript-regex) for this task 😆 
- `toISOString`
I've also modified `Date.UTC` so that it no longer calls out to the JS host.
> feat: implemented getters / setters and various string fns on Date 

- lib/loader/index.js
> Use F_NOEXPORTRUNTIME if __rtti_base is missing

- cli/asc.js
> Unify handling of transforms

- std/assembly/index.d.ts
I think the current description of `capacity` and `length` is not be equivalent, and the implementation here is `length`
> docs: change "capacity" to "length" for argument in Array's constructor

- src/compiler.ts
- src/resolver.ts
Emits an error diagnostic when calling a setter property. This case should be treated in the same way getters are treated. The issue is reproducible with the following code:
```ts
class B {
set prop(a: i32) {}
}
export function add(): void {
// Actual: assert
// Expected: error diagnostic specifying that this expression is not callable. 
(new B()).prop(1);
}
```
I emitted the diagnostic early, I'm assuming that there's no point in compiling the expression when this case is met as the setter expression is compiled when an assignment expression is found (might be wrong about this).
> fix: Fix assert when calling a setter property

- src/parser.ts
in Souce:
```ts
var internalPath = mangleInternalPath(normalizedPath);
```
in parseFile:
```ts
var normalizedPath = normalizePath(path);
var internalPath = mangleInternalPath(path);
```
I got two path string:
- ./examples/foo
- examples/foo
> fix: internalPath  in parseFile is not same with Source

- std/assembly/array.ts
- tests/compiler/class.untouched.wat
- tests/compiler/issues/1699.untouched.wat
- tests/compiler/std-wasi/process.optimized.wat
- tests/compiler/std-wasi/process.untouched.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/map.untouched.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/set.untouched.wat
> Minor post fix for #1841

- std/assembly/string.ts
- tests/compiler/std-wasi/process.optimized.wat
- tests/compiler/std-wasi/process.untouched.wat
- tests/compiler/std/string-casemapping.optimized.wat
- tests/compiler/std/string-casemapping.untouched.wat
- tests/compiler/std/string-encoding.optimized.wat
- tests/compiler/std/string-encoding.untouched.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/string.untouched.wat
> Move assert inside branch for String.fromCodePoint

- bin/asinit
> Autodetect ESM supports during asinit

- std/assembly/math.ts
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.ts
- tests/compiler/std/math.untouched.wat
Previous implementation  was incorrect for maximum mantissa values.
Edge cases current:
```ts
Math.round(+9007199254740991) -> +9007199254740992
Math.round(-9007199254740991) -> -9007199254740990
```
Edge cases fixed:
```ts
Math.round(+9007199254740991) -> +9007199254740991
Math.round(-9007199254740991) -> -9007199254740991
```
Fix #1856
> fix: More proper Math.round

- src/definitions.ts
- src/index.ts
Generated TypeScript definitions for WebAssembly modules are now flat, that is do not `export default ASModule` anymore, but the module members directly, with the `ASModule` namespace removed.
fixes #1705
> BREAKING CHANGE: Flatten generated TypeScript definitions

- src/builtins.ts
The instructions
* `v128.load32_lane`, `v128.store32_lane`, `v128.load32_zero`
* `v128.load64_lane`, `v128.store64_lane`, `v128.load64_zero`
can be used for the types `f32` respectively `f64` as well.
> Support floats in SIMD load/store lane/zero

- std/assembly/math.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/math.ts
- tests/compiler/std/math.untouched.wat
- tests/compiler/wasi/seed.optimized.wat
- tests/compiler/wasi/seed.untouched.wat
Some negative inputs for `acosh` may produce non-NaN values while all range `x < 1` should always return NaN. This PR fix this.
Thanks to @Yaffle for finding this [edge case](https://github.com/AssemblyScript/assemblyscript/issues/1856#issuecomment-850974607)
> fix: Fix negative inputs of Math.acosh

- scripts/build-dts.js
- src/builtins.ts
- src/compiler.ts
- src/flow.ts
- src/glue/binaryen.d.ts
- src/glue/tsconfig.json
- src/module.ts
- src/passes/ministack.ts
- src/passes/pass.ts
- src/passes/rtrace.ts
- src/passes/shadowstack.ts
- src/resolver.ts
- src/tsconfig.json
- src/types.ts
* Removes redundant bindings for Binaryen constants (no need to maintain these)
* Renames the oddly named `NativeType` to `TypeRef`
* Makes the binding's type definitions the single source of truth
* Adds comments for reference
> Refactor and clean up Binaryen bindings

- std/assembly/builtins.ts
Hello!
This is just something I noticed when working on the [Fastly AS SDK](https://www.npmjs.com/package/@fastly/as-compute).
It seems like in version `0.18.13`, we introduced a change in which caused a type error, as we try to assign `void` to an `i32`, and `i31ref`:
I got the error above when running typedoc on version `0.19.1`, but it works again on `0.18.12`. So, I assume unreachable is the instruction that causes things to crash. So instead of returning void, I still call the function, but return a "void number" (0), which I assume is the expected behavior?
With this fix, things start working again in the type system:
Thanks to whoever picks up this review! 😄 🎉 
cc @dcodeIO @MaxGraey 😄
> Fixed stdlib builtins not working with typedoc

- src/definitions.ts
With the definitions now being in a format that can be picked up by bundlers (anticipating ESM integration) even when not using the loader, it may be useful to also declare the memory and the table, as well as exported runtime helpers.
* `memory` if exported
* `table` if exported
* `_start` if explicit
* `__new`, `__pin`, `__unpin`, `__collect` and `__rtti_base` if exported
* `__setArgumentsLength` if there are exported varargs functions
Also fixes #1900
> Include env/RT in generated definitions

- tests/compiler/rereexport.ts
relates to #1894 
Per our discussion in the meeting: https://github.com/AssemblyScript/core/issues/65 , this just cuts a release for #1894 , by adding some periods to comments I wrote in a test 😄
> fix: Make a patch release for #1894

- bin/asinit
After landing #1776 we forget make same changes for asinit.
> fix: use shrinkLevel: 0 for asinit default config

- NOTICE
- std/assembly/index.d.ts
> fix type declarations

- NOTICE
- src/compiler.ts
- src/resolver.ts
I'm not exactly sure what the current status of the spread operator is, but I noticed that the compiler crashes when using it
fixes #1853
all tests passed in my fork
> Throw unimplemented error when using spread operator

- src/compiler.ts
If constructors of exported classes are inlined and require a varargs stub, we were missing to make sure that the varargs stub has something to call. This change simply allows inlining the original function into the stub.
fixes #1820
> Allow inlining the original function into its varargs stub

- std/assembly/index.d.ts
> Annotate that the ERROR macro terminates execution

- std/assembly/util/sort.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.untouched.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/typedarray.untouched.wat
After some new changes in algo (optimize memory usage), I decided to recheck boundary for insertion sort and found (Chrome baseline) that it had moved down.
> std(sort): reduce INSERTION_SORT_THRESHOLD constant to 48

- src/compiler.ts
- tests/compiler/class-overloading-cast.json
- tests/compiler/class-overloading-cast.optimized.wat
- tests/compiler/class-overloading-cast.ts
- tests/compiler/class-overloading-cast.untouched.wat
fixes #1971
Generic base classes have an issue where all instances regardless of generic are collected as instances of its virtual methods.  This checks to make sure that only methods from classes that extend the generic base class are added to the virtual table.
> fix: check function's instance class is a subclass of virtual method

- src/compiler.ts
- tests/compiler/export-generic.json
Because of tree shaking unused methods or class aren't compiled so there is no need to warn about unimplemented instances.
> fix: Make warning 232 pedantic

- NOTICE
- lib/loader/index.d.ts
- lib/loader/index.js
- lib/loader/tests/index.js
> feat: add __newArrayBuffer() to the loader

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- tests/compiler/export-generic.json
> Renumber now-pedantic diagnostic from 232 to 907

- cli/asc.js
- src/module.ts
> fix: Remove runPass and use runPasses only

- NOTICE
- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/flow.ts
- add a diagnostic message:  `Cannot redeclare block-scoped variable '{0}'`, when variants scope re-declare, throw out following message instead of abort:
ERROR TS2451: Cannot redeclare block-scoped variable 'a'
let a = a + b;
~~~~~~~~~~~~~
in assembly/index.ts(4,3)
- add my name and email in NOTICE
> fix: add redeclare variable error message (#1987)

- src/compiler.ts
- tests/compiler/unknown-bool-ident.json
- tests/compiler/unknown-bool-ident.ts
`getExpressionType` can return Unreachable type if expression passed is invalid
fixes #1990
> fix: Expression passed to `evaluateCondition` asserted to be valid

- src/compiler.ts
example:
```ts
{ class InnerClass {} }
```
Output:
```
ERROR AS100: Not implemented: Block-scoped class declarations or expressions
{ class InnerClass {} }
~~~~~~~~~~~~~~~~~~~
```
> fix: proper error for block scoped class expressions

- src/extra/ast.ts
Now `export * from "xx"` will be built to `export {} from "xx"`.
@willemneal  visitor-as also has this problem.
It makes the behavior of the compiler plug-in difficult to understand, because there may be many files that are modified.
> fix(astBuilder): fix export statment

- src/flow.ts
- tests/compiler/enum-return-error.json
- tests/compiler/enum-return-error.ts
Fixes #2031
LMK if you know a better way of reworking the assert!
> Fix flow.canOverflow when checking EnumValue

- bin/asinit
Use -w or --web to use only the web template. Use -w -n or --web --node to use both.
> Add web template to asinit

- src/compiler.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/class-overloading-cast.untouched.wat
- tests/compiler/class-overloading.untouched.wat
Should fix #2034 by first compiling virtual overload dependencies so late cross-dependencies are not missed during stub finalization.
> Compile virtual dependencies before finalizing stubs

- src/compiler.ts
- tests/compiler/managed-cast.optimized.wat
- tests/compiler/managed-cast.untouched.wat
Fixes #2035 by bypassing `null` values in emitted runtime upcast checks (which `__instanceof` naturally cannot handle) while keeping the current behavior as a simplification where the value can be statically determined to be non-null.
> Properly handle nulls in runtime upcast checks

- std/assembly/index.d.ts
> fix: Fix internal hints in definitions

- lib/loader/tests/index.js
Just the two trivial test cases from https://github.com/AssemblyScript/assemblyscript/pull/1913.
> Cherry pick some loader string test cases

- src/parser.ts
Fixes #1999, where in ```skipBlock(tn: Tokenizer): void```,  the condition of  ```Token.TEMPLATELITERAL``` is missing and ```tn.next()``` also don't go to the next token. It causes infinite loop.
> fix: when parser error, infinite loop in skipStatement (#1999)

- src/flow.ts
- tests/compiler/function-expression-error.json
- tests/compiler/function-expression-error.ts
Fixes https://github.com/AssemblyScript/assemblyscript/issues/2036. The assertion there has bitten us a couple times already, so I figured it is probably best to remove.
> Fix flow assertion on invalid function expression

- src/program.ts
- tests/compiler/field-initialization-errors.json
- tests/compiler/field-initialization-warnings.json
- tests/compiler/field.json
- tests/compiler/field.optimized.wat
- tests/compiler/field.ts
- tests/compiler/field.untouched.wat
Fixes #2006 where it turned out that internal field names always used static property notation, then conflicting with other static members resulting in an assertion.
> Internal field names should use instance notation

- std/assembly/array.ts
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/array.ts
- tests/compiler/std/array.untouched.wat
Fixes #2018 where it was discovered that `Array#flat` erroneously used the backing buffer's byteLength instead of its length, leading to an OOB `memory.copy` into subsequent data.
In the concrete repro, the array header was overwritten with zeroes, leading to the reported effect when the backing buffer is larger than the length, say after a resize triggered by `push`.
> Use correct data length in Array#flat

- std/assembly/bindings/wasi.ts
- std/assembly/process.ts
- std/assembly/wasi/index.ts
- tests/compiler/std-wasi/console.optimized.wat
- tests/compiler/std-wasi/console.untouched.wat
- tests/compiler/std-wasi/crypto.optimized.wat
- tests/compiler/std-wasi/crypto.untouched.wat
- tests/compiler/std-wasi/process.optimized.wat
- tests/compiler/std-wasi/process.untouched.wat
- tests/compiler/wasi/seed.optimized.wat
- tests/compiler/wasi/seed.untouched.wat
This fixes an issue with wasi/seed where if all memory is optimized away there can be an OOB access at offset 0 (unlikely in real programs), while moving the previous shared `iobuf` up to become a general shared buffer for these kinds of tasks.
> Use shared temporary buffer for WASI out values

- src/compiler.ts
- tests/compiler/ternary.optimized.wat
- tests/compiler/ternary.ts
- tests/compiler/ternary.untouched.wat
Fixes #1960 by special-casing compilation of ternary ifs where contextual type is void, dropping each arm evaluating to a concrete value, including ignoring type mismatch if not relevant.
> Allow void ternary expressions

- std/assembly/index.d.ts
- std/assembly/staticarray.ts
- tests/compiler/std/staticarray.optimized.wat
- tests/compiler/std/staticarray.ts
- tests/compiler/std/staticarray.untouched.wat
+ Fix some tests in StaticArray
> feat: Add StaticArray#sort

- cli/asc.js
Related to #1731 where a Binaryen exception suppresses the stack trace, then crashing the crash handler. Now prints a half-way meaningful message hinting at what to look for.
> Handle compiler crash where there is no stack trace

- src/compiler.ts
Fixes #1731 by making sure that class id exports aren't added twice, which can happen when an imported file is also a yet unprocessed entry file.
> Properly skip duplicate class id exports

- src/compiler.ts
- tests/compiler/templateliteral.optimized.wat
- tests/compiler/templateliteral.ts
- tests/compiler/templateliteral.untouched.wat
Fixes #1944 where in the general case reusing a StaticArray, when the same expression is recursively involved in subexpressions, preparing the subexpression (using the same StaticArray) could overwrite yet unprocessed values before the outer `.join("")` is performed.
> Fix value confusion in recursive template literals

- src/builtins.ts
- tests/compiler/unmanaged-errors.json
- tests/compiler/unmanaged-errors.ts
Fixes #2067 where a managed / unmanaged mismatch is diagnosed but before it is reported triggers an assertion in runtime visitor logic.
> Defuse assertion when mixing managed and unmanaged classes

- src/builtins.ts
- src/compiler.ts
- src/module.ts
- tests/compiler/closure.json
- tests/compiler/closure.ts
Fixes #2073 by removing error-prone automatic type detection when emitting a select expression. Was a legacy option anyway, from a time where `select`s didn't specify a type.
> Remove automatic type detection when emitting a select

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
More and more libraries provide transform, I think there should be a more unified message, `User-defined` I think it is too vague, we need to point out the name of the specific transform.
> feat: add Transform_0_message_1 for transform developer

- src/compiler.ts
- src/module.ts
A while ago Binaryen introduced a `copyExpression` helper that we can reuse. The previous `cloneExpression` now is merely a special case of it, `tryCopySimpleExpression`.
> Refactor cloneExpression to reuse copyExpression

- snap/README.md
- snap/snapcraft.yaml
I don't really know what I'm doing here, mostly taken from the [snapcraft.yaml reference](https://snapcraft.io/docs/snapcraft-yaml-reference). Does anyone have experience with this? :)
> Update snap build

- src/parser.ts
Fixes #2082 where it was discovered that the `new` token is incorrectly handled as a non-starting token.
> NEW token should not participate in non-starting precedence

- src/glue/binaryen.d.ts
- src/module.ts
In general it should speedup on 12-20% for UTF8 interop methods
> Slightly optimize interop with binaryen

- src/module.ts
`u = 0x10000 + ((u & 0x3FF) << 10) | (str.charCodeAt(++i) & 0x3FF);`
don't need anymore
> Simplify stringLengthUTF8 more

- src/resolver.ts
I guess before integer pow came along, we had slightly different resolvers. But now the power operation should be handled the same way as all the others, the actual body of the handlers is one and the same, so I decided to transfer this to all the others.
> [refactoring] move Token.ASTERISK_ASTERISK to general group in resolveBinaryExpression

- src/compiler.ts
- src/flow.ts
⯈fix issue: do-while + switch + continue cause compiler crash #2101
⯈when `compileSwitchStatement`, `commonConditional` don't consider the situations that `CONTINUES` should change to `CONDITIONALLY_CONTINUES` in `FlowFlags`.
> fix: compileSwitchStatement will hide inner conditional flags

- NOTICE
- cli/util/options.js
Environment:
assemblyscript: 0.19.17
platform: macos
cmd: yarn asbuild
asconfig: 
```js
{
// ...someting not important
options: {
"transform": "./transform.ts"
}
}
```
The segment of options.js
```javascript
function resolvePath(p, baseDir, useNodeResolution = false) {
if (path.isAbsolute(p)) return p;
if (useNodeResolution && !p.startsWith(".")) {
return dynrequire.resolve(p, { paths: [ baseDir ] });
}
return path.join(baseDir, p);
}
```
The default value of `baseDir` is `.`. When p is relative path, then ...
```typescript
path.join(".", "./transform.ts"); // The result is 'transform.ts'. It lost the information about relative
```
> fix: transform cannot find module

- src/compiler.ts
- tests/compiler/overflow.ts
- tests/compiler/overflow.untouched.wat
> fix: Fix boolean oveflow casts for constants

- src/module.ts
Fixes some old code inherited from Emscripten around the initial commit, that is [not handling surrogates correctly](https://github.com/emscripten-core/emscripten/issues/15324). Did not surface so far because it is only used to call Binaryen APIs with constant names respectively identifiers coming from the parser. For now retains the assumption that WTF-8 is fine with Binaryen/C++ (`const char*`, `std::string`, ...).
> Fix Binaryen glue string encoding

- src/compiler.ts
- src/flow.ts
- tests/compiler/features/simd.optimized.wat
- tests/compiler/features/simd.ts
- tests/compiler/features/simd.untouched.wat
It allow do this now:
```ts
export function foo(x: v128): i32 {
if (x) { // internally uses v128.any_true(x)
return -1;
}
return 0;
}
```
> feat: Add trueish conversion for v128 types

- lib/sdk/index.js
We've recently switched to long.js 5.1, which has a slightly different directory structure.
> SDK: Update long.js CDN path

- src/tsconfig.json
This set `useDefineForClassFields` to `false`. See:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier
Which significantly speedup TS and it's emits.
> Add useDefineForClassFields = false and some extra check flags

- src/ast.ts
- src/tokenizer.ts
- src/util/binary.ts
- src/util/text.ts
> Refactor text utils

- src/module.ts
- src/tokenizer.ts
- src/util/text.ts
Refactors surrogate code point helpers to text util for reuse.
> Refactor text util surrogate helpers

- tests/compiler/features/reference-types.optimized.wat
- tests/compiler/features/reference-types.ts
- tests/compiler/features/reference-types.untouched.wat
Fixes what seems to be a typo leading to test failure in the `features/reference-types` test. Probably didn't surface so far because we couldn't really run the test, but now it works.
> Fix reference-types test failure

- src/parser.ts
- tests/parser/type.ts
- tests/parser/type.ts.fixture.ts
Add parsing this valid TS syntax:
```ts
type Maybe<T> = | T | null;
```
or
```ts
type Maybe<T> = 
| T 
| null;
```
> Skip leading bar during type's declaration

- src/module.ts
- src/passes/shadowstack.ts
> Optimize expandType for JS target

- src/module.ts
- tests/compiler/NonNullable.optimized.wat
- tests/compiler/call-super.optimized.wat
- tests/compiler/class-overloading.optimized.wat
- tests/compiler/memset.optimized.wat
- tests/compiler/number.optimized.wat
- tests/compiler/resolve-access.optimized.wat
- tests/compiler/resolve-binary.optimized.wat
- tests/compiler/resolve-elementaccess.optimized.wat
- tests/compiler/resolve-ternary.optimized.wat
- tests/compiler/std-wasi/crypto.optimized.wat
- tests/compiler/std-wasi/process.optimized.wat
- tests/compiler/std/array.optimized.wat
- tests/compiler/std/arraybuffer.optimized.wat
- tests/compiler/std/date.optimized.wat
- tests/compiler/std/map.optimized.wat
- tests/compiler/std/math.optimized.wat
- tests/compiler/std/mod.optimized.wat
- tests/compiler/std/set.optimized.wat
- tests/compiler/std/string-casemapping.optimized.wat
- tests/compiler/std/string-encoding.optimized.wat
- tests/compiler/std/string.optimized.wat
- tests/compiler/std/typedarray.optimized.wat
- tests/compiler/std/uri.optimized.wat
- tests/compiler/templateliteral.optimized.wat
- tests/compiler/wasi/trace.optimized.wat
> Improve pass pipeline. Refactor code folding

- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
- src/extra/ast.ts
- src/parser.ts
- tests/parser/also-identifier.ts
- tests/parser/also-identifier.ts.fixture.ts
- tests/parser/class.ts
- tests/parser/class.ts.fixture.ts
https://github.com/AssemblyScript/assemblyscript/pull/2158#discussion_r757962361 suggests to allow the parser to understand the `declare` modifier, but mark it as unsupported when parsed.
> Add `declare` to parser

- src/builtins.ts
- src/compiler.ts
- src/module.ts
> Add tableName for indirect calls

- lib/loader/index.js
- lib/loader/umd/index.js
> loader: Fix TypedArray view not considering .byteLength of slices

- src/compiler.ts
- src/diagnosticMessages.generated.ts
- src/diagnosticMessages.json
Passing a generic function by value previously diagnosed a mismatch in argument count, which was not very helpful. Now diagnoses that a **type** argument was expected, *and* that the expression does not compile to a value at runtime.
See #2081.
> Diagnose better error when using generic function by value

- .github/workflows/test.yml
CI on Windows hosts is currently broken due to an [npm bug](https://github.com/npm/cli/issues/4234), but seems to be fixed in newer npm versions. Right now, however, the Node install coming with Node on Windows hosts comes with a broken version. Can be enabled again once that's not the case anymore.
> Disable CI on Windows

- src/compiler.ts
- src/module.ts
- src/util/binary.ts
> Mitigate crash on arrays of void or v128

- cli/index.js
Reverts AssemblyScript/assemblyscript#2234 since a fix for the polyfill is now available
> Revert "Try to work around an issue when polyfilling import maps"

- src/builtins.ts
- src/compiler.ts
- src/module.ts
- tests/compiler/features/gc.debug.wat
- tests/compiler/features/gc.release.wat
- tests/compiler/features/gc.ts
- tests/compiler/features/reference-types.debug.wat
- tests/compiler/features/reference-types.release.wat
- tests/compiler/features/reference-types.ts
Fixes #2209. Does not yet tackle the issue when using (experimental) GC types like `dataref`, which currently leads to a(n expected) Binaryen crash due to nullability not being up-to-date. Already works for `anyref`, though, as it is nullable.
> Fix crash on reference typed constant

- src/compiler.ts
- tests/compiler/resolve-binary.debug.wat
- tests/compiler/resolve-binary.release.wat
- tests/compiler/resolve-binary.ts
> Fix invalid assumption when compiling binary overloads

- std/assembly/date.ts
- std/assembly/index.d.ts
- tests/compiler/std/date.debug.wat
- tests/compiler/std/date.release.wat
- tests/compiler/std/date.ts
Fixes #2229 and related tests. Not sure what exactly is being tested with these huge timestamps (year 252309), though, so I'm not particularly confident regarding the assertion changes  :) @ColinEberhardt, any idea?
> Fix setUTCMonth check off by one

- lib/loader/package.json
Node.js v12.0.0 doesn't support conditional exports, so when it sees that `main` (`index.js`) is using ESM syntax it will throw a `SyntaxError` and prevent loading the module.
This PR sets `main` to use the UMD module so that old runtimes will be able to load the most compatible version. This will have no effect on ESM users since they can support conditional exports and will load `exports.import` (`./index.js`).
The earliest version of Node.js that can use this module in its current state is v12.20.0.
> Support Node.js v12.0.0 in @assemblyscript/loader

- NOTICE
- src/bindings/js.ts
- src/bindings/tsd.ts
> #2243 function expression as rhs in assignment

- NOTICE
- std/assembly/index.d.ts
This PR is to fix the red squigglies that I've noticed appearing in the `tsconfig.json` when upgrading from version `0.19.23` to `0.20.4`. 
The error is `Cannot find global type 'Number'`.
⯈
⯈
⯈
- [ x] I've read the contributing guidelines
- [ x] I've added my name and email to the NOTICE file
> Fix: Cannot find global type 'Number'

- src/bindings/js.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.release.js
Node.js 18 introduces `fetch` but not (yet) `WebAssembly.compileStreaming`.
> Fix bindings on Node.js 18

- std/assembly/index.d.ts
> Fix `process.exitCode`’s description.

- std/assembly/index.d.ts
In #2260 , `Number` was declared as `typeof F64` (equivalent to `typeof _Float`), which causes all numbers to be considered as a `Class` with some methods that don't belong to it, just like:
I updated the declaration of `Number` according to the [document](https://www.assemblyscript.org/stdlib/number.html#instance-members). I think this is a small change, so I submit PR directly.
⯈
⯈
⯈
> Fix: Incorrect type declaration about 'Number'

- src/builtins.ts
- src/compiler.ts
- src/diagnostics.ts
- src/flow.ts
- src/module.ts
- src/program.ts
- src/resolver.ts
- src/types.ts
Superseding this PR: #1761
String interpolation should be faster both on the v8 (JS) side and in bootstrap (AS)
> Refactor to string interpolation where possible in compiler

- std/assembly/index.d.ts
- std/portable/index.d.ts
> fix: Fix wrong param type in definitions for String.fromCharCodes

- src/resolver.ts
----
`nameInclTypeParamters` -> `nameInclTypeParameters`
> fix: Fix variable name typo in `resolveClass`

- bin/asc.js
Fix #2311
⯈receive error correctly from `main`
⯈pass the exit code from `spawnSync`
> fix: 'asc' will not exit with exit code 1 after compile failing(#2311)

- src/passes/shadowstack.ts
- tests/compiler/return-unreachable.debug.wat
- tests/compiler/return-unreachable.json
- tests/compiler/return-unreachable.release.wat
- tests/compiler/return-unreachable.ts
⯈fix #2187
⯈support `return unreachable()`
⯈avoid compile wat like (return (unreachable)) and then insert shadowstack instrument like (locals.get (unreachable))
> Fix unreachable in block statement

- src/diagnosticMessages.json
- src/parser.ts
- tests/parser/type.ts
- tests/parser/type.ts.fixture.ts
> fix: Disallow type recursion during type declaration

- std/assembly/map.ts
- std/assembly/set.ts
- tests/compiler/issues/2322/index.release.wat
- tests/compiler/return-unreachable.release.wat
- tests/compiler/std-wasi/process.debug.wat
- tests/compiler/std-wasi/process.release.wat
- tests/compiler/std/map.debug.wat
- tests/compiler/std/map.release.wat
- tests/compiler/std/set.debug.wat
- tests/compiler/std/set.release.wat
> Use uncheked array access for Map#values/keys and Set#values methods

- cli/index.js
- tests/cli/options.js
> [cli] fallback to _start value for --exportStart if argument was skipped

- src/bindings/js.ts
- tests/compiler/bindings/esm.debug.d.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.debug.wat
- tests/compiler/bindings/esm.js
- tests/compiler/bindings/esm.release.d.ts
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/esm.release.wat
- tests/compiler/bindings/esm.ts
- tests/compiler/bindings/raw.debug.d.ts
- tests/compiler/bindings/raw.debug.js
- tests/compiler/bindings/raw.debug.wat
- tests/compiler/bindings/raw.release.d.ts
- tests/compiler/bindings/raw.release.js
- tests/compiler/bindings/raw.release.wat
Example:
```ts
export function test(): u64 {
return 18446744073709551614; // i64.const -2
}
```
Before:
```ts
assert(exports.test() == 18446744073709551614n) // -> fail due to return -2n
```
Now with this PR:
```ts
assert(exports.test() == 18446744073709551614n) // pass!
```
> fix: Add coercion for unsigned 64-bit types for bindings

- src/bindings/js.ts
- src/bindings/tsd.ts
- tests/compiler/bindings/esm.debug.d.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.release.d.ts
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/raw.debug.d.ts
- tests/compiler/bindings/raw.release.d.ts
> fix: Add memory & table for esm binding's exports

- src/compiler.ts
- src/flow.ts
- src/passes/findusedlocals.ts
- src/util/collections.ts
Benchmark results for 1M items (JS):
```
BitSet add: 7.995ms
BitSet has: 4.894ms
Set<i32> add: 15.898ms
Set<i32> has: 15.414ms
```
Benchmark results for 100M items (Wasm):
```
BitSet add: 39.5000
BitSet has: 29.3000
Set<i32> add: 194.6000
Set<i32> has: 207.3000
```
> Introduce more faster and memory optimal BitSet as replacment of Set<i32>

- src/resolver.ts
- tests/compiler/resolve-unary.debug.wat
- tests/compiler/resolve-unary.release.wat
- tests/compiler/resolve-unary.ts
⯈fix #2282
⯈add reolve typeof return to string
> fix: Fix resolve typeof type

- cli/index.js
- cli/options.json
⯈fix #2277
⯈add `--disableWarning` option to disable compilation warning
eg:
`--disableWarning 201` can disable warning 201
`--disableWarning` can disable all warnings
> feat: add `--disableWarning` option to disable compilation warning

- std/assembly/bindings/dom.ts
It should be a minimal set for some meaningful DOM manipulations
> feat: Add more document methods for bindings/dom.ts

- src/common.ts
- src/diagnosticMessages.json
- src/parser.ts
- src/program.ts
- src/tokenizer.ts
- tests/compiler/class-overloading-cast.ts
- tests/compiler/override-error.json
- tests/compiler/override-error.ts
- tests/parser/class.ts
- tests/parser/class.ts.fixture.ts
fix: #2353
add override keyword and type check
support following code
```typescript
class A {
method(): void {}
}
class B extends A {
override method(): void {}
// This member cannot have an 'override' modifier because it is not declared in the base class 'A'.
override method_error(): void {}
}
```
> feat: add override keyword

- src/bindings/js.ts
- tests/compiler/bindings/esm.debug.d.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.debug.wat
- tests/compiler/bindings/esm.release.d.ts
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/esm.release.wat
- tests/compiler/bindings/esm.ts
- tests/compiler/bindings/raw.debug.d.ts
- tests/compiler/bindings/raw.debug.js
- tests/compiler/bindings/raw.debug.wat
- tests/compiler/bindings/raw.release.d.ts
- tests/compiler/bindings/raw.release.js
- tests/compiler/bindings/raw.release.wat
fixes #2349, fixes #2283, fixes #2243
Related: #2255, which partly addressed lifting
> Support lifting/lowering of functions as internrefs

- src/diagnostics.ts
Tackles a few issues with diagnostic messages printed to console, plus making them a bit more pretty.
* Strip leading whitespace
* Account for tabs (use two spaces)
* Limit output to contents of first line so inner newlines don't break the formatting
> Improve diagnostic messages printed to console

- NOTICE
- std/assembly/index.d.ts
- tests/compiler/simd.debug.wat
- tests/compiler/simd.release.wat
- tests/compiler/simd.ts
according to the source code of `builtin_v128_pmin` and `builtin_v128_pmax`.
they only accept the f32 and f64 format, change the function signature according to its source code.
```  
if (type.isValue) {
switch (type.kind) {
case TypeKind.F32: return module.binary(BinaryOp.PminF32x4, arg0, arg1);
case TypeKind.F64: return module.binary(BinaryOp.PminF64x2, arg0, arg1);
}
}
compiler.error(
DiagnosticCode.Operation_0_cannot_be_applied_to_type_1,
ctx.reportNode.typeArgumentsRange, "v128.pmin", type.toString()
);
```
this issue found from issue [2374](https://github.com/AssemblyScript/assemblyscript/issues/2374)
> fix function signature of v128.pmin, v128.pmax

- src/diagnosticMessages.json
- src/program.ts
- tests/compiler/class-extends-itself.json
- tests/compiler/class-extends-itself.ts
> fix: class extends itself #2201

- src/resolver.ts
- std/assembly/index.d.ts
- tests/compiler/indexof-valueof.debug.wat
- tests/compiler/indexof-valueof.ts
> Improve valueof definitions. Add some extra tests

- std/assembly/date.ts
- tests/compiler/std/date.debug.wat
- tests/compiler/std/date.release.wat
New approach based on novel "Euclidean Affine Functions and Applications to Calendar Algorithms (2021)" implementation and **~1.6x** faster than old one.
[benchmark & validation on playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKbGV0IF9tb250aDogaTMyLCBfZGF5OiBpMzI7CgpAaW5saW5lIGZ1bmN0aW9uIGZsb29yRGl2PFQgZXh0ZW5kcyBudW1iZXI+KGE6IFQsIGI6IFQpOiBUIHsKICByZXR1cm4gKGEgPj0gMCA/IGEgOiBhIC0gYiArIDEpIC8gYiBhcyBUOwp9CgpleHBvcnQgZnVuY3Rpb24geW1kRnJvbUVwb2NoRGF5cyh6OiBpMzIpOiBpMzIgewogIHogKz0gNzE5NDY4OwogIHZhciBlcmEgPSA8dTMyPmZsb29yRGl2KHosIDE0NjA5Nyk7CiAgdmFyIGRvZSA9IDx1MzI+eiAtIGVyYSAqIDE0NjA5NzsgLy8gWzAsIDE0NjA5Nl0KICB2YXIgeW9lID0gKGRvZSAtIGRvZSAvIDE0NjAgKyBkb2UgLyAzNjUyNCAtIGRvZSAvIDE0NjA5NikgLyAzNjU7IC8vIFswLCAzOTldCiAgdmFyIHllYXIgPSB5b2UgKyBlcmEgKiA0 …
> Optimize util for calculation year, month, day in Date

- src/compiler.ts
From [2402](https://github.com/AssemblyScript/assemblyscript/issues/2402).
remove the dead code
> Remove dead code for compiler.ts

- src/program.ts
- src/types.ts
> Refactor types.ts

- src/bindings/tsd.ts
> fix: fix endless recursion during dts generation

- cli/options.json
> [cli] update exportRuntime option description

- NOTICE
- std/assembly/array.ts
- std/assembly/util/error.ts
> revert #1353: revert runtime type check to compile time check for `Array#flat`

- src/compiler.ts
Dead code issue from issue [2427](https://github.com/AssemblyScript/assemblyscript/issues/2427)
> Remove dead code of compiler.ts

- std/assembly/math.ts
- std/assembly/util/math.ts
- tests/compiler/binary.debug.wat
- tests/compiler/resolve-binary.debug.wat
- tests/compiler/std/math.debug.wat
- tests/compiler/std/math.release.wat
Motivation:
Right shifts makes sense mostly for single expressions or complex conditions. While single `if (x < 0)` or `select(..., x < 0)` usually fused to single instruction `js` / `jns` / `cmovs` / `cmovns` on wasm engines
> Refactor branch / select sign checks from rshift to cmp with zero

- src/compiler.ts
- src/util/vector.ts
> Add v128 case for makeNegOne

- src/builtins.ts
- src/compiler.ts
- src/flow.ts
- src/resolver.ts
- src/types.ts
Refactor binary / unary ISIZE / USIZE cases to use Size-agnostic op codes.
> [NFC] Refactor using size operations

- src/resolver.ts
- tests/compiler/infer-generic.debug.wat
- tests/compiler/infer-generic.release.wat
- tests/compiler/infer-generic.ts
fix error like this:
```typescript
class Ref {
x: i32;
}
// infer builtin assert generic
export function inferAssert(v: Ref | null): void {
assert(v).x;
}
```
> fix: assert throwing expected 2 arguments but got 1

- cli/index.js
It's pretty frequent mistake during migration from 0.19.x to 0.20.x.
> [cli] Prevent uses binaryFile in options

- src/ast.ts
- src/common.ts
- src/compiler.ts
- src/diagnostics.ts
- src/flow.ts
- src/index-wasm.ts
- src/module.ts
- src/parser.ts
- src/program.ts
- src/resolver.ts
- src/tokenizer.ts
- src/tsconfig.json
Some useful refactorings from #2161
> Reorganize & refactor diagnostic's utils. Add more const enums

- NOTICE
- src/glue/js/i64.d.ts
- I've read the contributing guidelines
- I've added my name and email to the NOTICE file
Fixed a type def for i64_signbit in https://github.com/AssemblyScript/assemblyscript/blob/3a5b51d184bf4dfc3c1a5e1d57481a1b0ce1a71d/src/glue/js/i64.d.ts#L51
> fix: Add missing type for i64_signbit input argument

- src/resolver.ts
- tests/compiler/std/array.ts
It makes `resolveFunctionExpression` can return correct function type for expression like `(x: i32) => x`
> fix: infer return type in implicit return arrow function

- src/resolver.ts
> [NFC] Minor refactorings for resolver

- src/builtins.ts
- src/module.ts
> Refactor RefIsOp and RefAsOp enums

- std/assembly/index.d.ts
> fix: Fix number of lines for f32x4.shuffle definition

- src/tokenizer.ts
- src/util/text.ts
Some useful refactorings segregated from #2460
> Minor refactorings for numeric parsing in tokenizer

- std/assembly/object.ts
- tests/compiler/std/object.debug.wat
This change significantly simplify `Object.is<f64 | f32>`.
```ts
Object.is(x, -0.0);
```
OLD codegen:
```wat
local.get $x
i64.reinterpret_f64
i64.const -9223372036854775808
i64.eq
local.get $x
f64.const -0
f64.eq
i32.and
)
```
NEW codegen:
```wat
local.get $x
i64.reinterpret_f64
i64.const -9223372036854775808
i64.eq
```
```ts
Object.is(x, NaN);
```
OLD codegen:
```wat
local.get $x
i64.reinterpret_f64
i64.const 9221120237041090560
i64.eq
local.get $x
local.get $x
f64.ne
local.get $x
f64.const nan:0x8000000000000
f64.eq
select
```
NEW codegen:
```wat
local.get $x
i64.reinterpret_f64
i64.const 9221120237041090560
i64.eq
local.get $x
local.get $x
f64.ne
i32.or
```
> Simplify floating points comparison for Object.is

- src/module.ts
The `[Expression]Id` getters are [generated programmatically](https://github.com/WebAssembly/binaryen/blob/da24ef6ed7055f64299fce22a051ba0e85284c23/src/binaryen-c.h#L172-L175) by Binaryen nowadays, so already exist in the version of Binaryen we use - all that's left is to add them.
> Add stringref expression ids

- tests/compiler/std/math.debug.wat
- tests/compiler/std/math.release.wat
- tests/compiler/std/math.ts
> Improve math tests by using Object.is for -0.0 checks

- tests/tokenizer.js
very simple change that the tokenizer.js test file using incorrect file name.
> fix: incorrect filename of the test of tokenizer

- std/portable/index.js
Previous one  can't properly handle such edge cases:
```ts
copysign(1.0, +0.0)   ->  +0.0
copysign(1.0, -0.0)   ->  -0.0
copysign(1.0, +NaN)   ->  NaN
copysign(1.0, -NaN)   ->  NaN
```
Now, these cases don't change destination `x` argument. Only its sign:
```ts
copysign(1.0, +0.0)   ->  +1
copysign(1.0, -0.0)   ->  -1
copysign(1.0, +NaN)   ->  +1
copysign(1.0, -NaN)   ->  -1
```
> fix: Use proper portable copysign polyfill

- cli/index.js
⯈using `npx asc` will transform the path from `a\b` to `a\\b`, so the entry path replace reg should be changed from `/\\/g` to `/\\+/g`
> fix: support windows format path (#2262)

- tests/compiler/binary-error.json
- tests/compiler/binary-error.ts
Hi Maintainer,
I found the some tests are missed for binary expression, please decide if we need to coverage this part? and please review the below tests are suitable?
Regards
> fix: add more test coverage for binary expression

- NOTICE
- src/compiler.ts
- tests/compiler/inlining.debug.wat
- tests/compiler/inlining.release.wat
- tests/compiler/inlining.ts
This change allows calls like `a(a(a(1)))` to be @inlined properly.
> Push to the inline stack after compiling arguments

- src/compiler.ts
- src/types.ts
- tests/compiler/features/gc.debug.wat
- tests/compiler/features/gc.release.wat
- tests/compiler/features/gc.ts
Resolves a TODO that is now possible to tackle with heap types.
> Implement non-/nullable type refs in type conversion

- src/resolver.ts
- tests/compiler/duplicate-field-errors.json
- tests/compiler/duplicate-field-errors.ts
- tests/compiler/duplicate-fields.debug.wat
- tests/compiler/duplicate-fields.release.wat
- tests/compiler/duplicate-fields.ts
Discovered in #2537: #2158 introduced unsoundness by making class fields covariant, which is also incompatible with Wasm GC where mutable fields are required to be invariant.
As Wasm GC states:
> Structure types support width and depth subtyping
> 
> * `struct <fieldtype1>* <fieldtype1'>* <: struct <fieldtype2>*`
>   * iff `(<fieldtype1> <: <fieldtype2>)*`
> Field types are covariant if they are immutable, invariant otherwise
> 
> * `const <valtype1> <: const <valtype2>`
>   * iff `<valtype1> <: <valtype2>`
> * `var <valtype> <: var <valtype>`
> * Note: mutable fields are not subtypes of immutable ones, so const really means constant, not read-only
Example of the problem:
```ts
class Animal {
sibling: Animal;
}
class Cat extends Animal {
sibling: Cat; // unsound
}
class Dog extends Animal …
```
> fix: Make field types invariant for soundness

- cli/index.js
Hi Maintainer,
I found customer runtime error log only contains the runtime path, actually the calculated path should contains the `baseDir` and `extension` information.
regards
> fix: more information for runtime error

- std/assembly/rt/tlsf.ts
Seems these were a historic artifact pre null checking.
> Remove superfluous casts in TLSF

- scripts/build-web.js
Generates two additional files as part of the web template: `importmap.json` containing the import map, and `importmap.js` exporting the import map. Should help to automate setting up the compiler without manually editing versions, as we currently do on the website.
> Expose import maps when generating web template

- src/compiler.ts
- src/program.ts
Moves creation of the module to the program, which is the common link between all of parser, resolver, compiler *and* module. With the change, it for example becomes possible to assign names of program elements when building compound types for classes and signatures, where previously there was a missing reference to the module (type => program !=> module) the names are supposed to be added to.
> Move module creation to program

- src/glue/binaryen.d.ts
- src/glue/binaryen.js
- src/module.ts
> Add heap type utility definitions

- .github/workflows/publish.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- NOTICE
1. update actions/checkout to v3 https://github.com/actions/checkout/blob/main/CHANGELOG.md
2. update actions/stale to v6 https://github.com/actions/stale/blob/main/CHANGELOG.md
>  ci: update github actions

- .github/workflows/publish.yml
Follow-up to #2541. Recent versions of `actions/checkout` fetch with `depth=1`, then missing commit history and tags necessary for publishing.
> Fix CI publishing

- src/compiler.ts
- src/diagnosticMessages.json
- src/resolver.ts
- tests/compiler/assert-nonnull.debug.wat
- tests/compiler/assert-nonnull.release.wat
- tests/compiler/std/array-access.debug.wat
- tests/compiler/std/array-access.release.wat
- tests/compiler/std/array-access.ts
An alternative to #2530 that instead simplifies the logic in `compileCallExpression`: Any call that is not a direct call compiles the target expression for use as the function argument of an indirect call.
cc @CountBleck 
Fixes #2530, fixes #2525
> Simplify compileCallExpression

- src/resolver.ts
Fixes #2565, where if a field type failed to resolve earlier, the field should be skipped when finalizing the class.
> Defuse assert in finishResolveClass

- src/bindings/js.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/raw.debug.js
- tests/compiler/bindings/raw.release.js
Fixes #2553 by using a helper function when lowering (what's typically) another lowering to memory:
```ts
new Uint32Array(memory.buffer)[pointer >>> 2] = __lowerXY(...);
// ->
__store_ref(pointer, __lowerXY(...));
```
Changes evaluation order so the LHS view is not invalidated by memory growth in the RHS before the store is performed.
> Bindings: Expect memory growth when lowering references

- std/assembly/array.ts
- tests/compiler/bindings/esm.debug.wat
- tests/compiler/bindings/raw.debug.wat
- tests/compiler/infer-array.debug.wat
- tests/compiler/infer-array.release.wat
- tests/compiler/issues/1699.debug.wat
- tests/compiler/std/array-literal.debug.wat
- tests/compiler/std/array-literal.release.wat
- tests/compiler/std/array.debug.wat
- tests/compiler/std/array.release.wat
- tests/compiler/std/date.debug.wat
- tests/compiler/std/date.release.wat
- tests/compiler/std/map.debug.wat
- tests/compiler/std/map.release.wat
- tests/compiler/std/set.debug.wat
- tests/compiler/std/set.release.wat
- tests/compiler/std/static-array.debug.wat
- tests/compiler/std/string.debug.wat
- tests/compiler/std/string.release.wat
Turned up in #2575, where if `--uncheckedBehavior always` is given, an `array[index] = ...`, when setting an `index >= length`, does not ensure that the array has enough capacity. Code might however expect that this basic contract holds regardless. Hence this PR removes unchecked indexed set on normal arrays. Does not change fixed sized arrays, where there is no such side-effect to retain.
> Remove unchecked indexed set on normal arrays

- src/bindings/js.ts
- src/bindings/tsd.ts
- src/builtins.ts
- src/compiler.ts
- src/program.ts
- src/types.ts
- tests/compiler/instanceof.debug.wat
- tests/compiler/instanceof.release.wat
- tests/compiler/instanceof.ts
Addresses #2577. One rather trivial part of the issue was that previously, since interfaces are not derived from `Object` but their implementing classes are, an `someInterface as Object instanceof SomeInterface` would fail. Another was that the check for when a cast may possibly succeed was overly simplistic, thus required more elaborate infrastructure.
The seemingly obvious alternative that doesn't work is to simply fall back to do dynamic checks if the relationship between the types is arbitrarily complicated (and hence possibly costly to compute), since that breaks assumptions about such checks being precomputable.
Making a draft for now while I untie the knot in my brain before figuring out how to best test the changes. Is perfectly possible that I missed something, hence I'd …
> Do precise subtype tests in instanceof

- NOTICE
- std/assembly/index.d.ts
Use constructor signature for `@unmanaged` and `@final` instead of `Function`.
This removes the need to use `// @ts-ignore: decorator` to suppress error from tsserver (used for code completion) while using the `assembly.json` config.
`Function` in `assembly` is different from `portable` so a class type signature inferred by Typescript is not assignable to `Function`.
> Use constructor signature for class decorators

- package.json
- src/bindings/js.ts
The Rtrace utility to inspect the inner workings of the runtime must be installed on the respective imports objects, which did not work as-is with ESM bindings
Hence, add a special case to ESM bindings generation to install Rtrace when used, exclude its imports from instrumentation, and import it with a private package specifier so it can be mapped via `imports` in package.json. Also unbreaks `bootstrap:rtraced` in so far as that it executes.
> Integrate Rtrace with ESM bindings

- cli/index.js
- cli/options.json
- src/builtins.ts
- src/compiler.ts
- src/flow.ts
- src/index-wasm.ts
This new option allows users to use unchecked() as usual, ignore it
entirely, and force unchecked contexts everywhere. Ignoring unchecked
is useful for debugging, and, if you're certain you want to accept the
risk, forcing unchecked could be beneficial for performance.
> Add --uncheckedBehavior to customize the use of unchecked() contexts

- src/parser.ts
- tests/parser/function-type.ts
- tests/parser/function-type.ts.fixture.ts
> Support trailing comma in function types

- scripts/build-web.js
Using the AssemblyScript compiler on the Web currently requires multiple steps to make it work, which includes manually updating the import map on version bumps and optionally providing a shim for import maps. Instead of providing a workaround by exposing the import map in a script plus longish instructions, this PR changes the mechanism to a single script that sets everything up.
Usage is
```html
<script src="https://cdn.jsdelivr.net/npm/assemblyscript@latest/dist/web.js"></script>
<script type="module">
import asc from "assemblyscript/asc";
...
</script>
```
where `latest` can be any version since the change, and additional query parameters can be used to modify behavior:
* `web.js?noinstall` does not install the import map
* `web.js?noshim` does not install the import map shim
* Both …
> feat: Provide an easily reusable Web SDK

- std/assembly/index.d.ts
- std/portable/index.d.ts
- std/portable/index.js
> Add parse methods to portable. Also fix couple type definitions

- src/compiler.ts
- src/parser.ts
- src/resolver.ts
- tests/compiler/in.json
- tests/compiler/in.ts
Addresses (only) the assertion seen in #2628, where parsing an unsupported complex type ends up interpreting the input as a yet unsupported `in` operator. Adds the `in` operator as a case of `BinaryExpression` for now that is then diagnosed as AS100 Not implemented.
> Diagnose not yet implemented 'in' operator

- src/bindings/util.ts
- tests/compiler/bindings/esm.ts
Fixes #2611 (I suppose), where it was discovered that some possible export kinds are not yet handled when walking exports during bindings generation, most notably exported interfaces.
> Handle all possible element kinds when walking exports

- src/ast.ts
- src/parser.ts
- src/resolver.ts
- tests/compiler/typerecursion.json
- tests/compiler/typerecursion.ts
- tests/parser/type.ts.fixture.ts
Fixes #2633 by detecting recursive types, that are not supported yet. during resolve. Also touches detection of circular type aliases, which is related, simplifying the code a bit.
> Detect recursive types early

- src/builtins.ts
- src/compiler.ts
- src/module.ts
- src/program.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
- std/assembly/memory.ts
- std/assembly/number.ts
Addresses https://github.com/AssemblyScript/assemblyscript/pull/2632#pullrequestreview-1267379884 by only allowing `@builtin` decorators if there actually is such a builtin, effectively preventing that the decorator is used otherwise. Also refactors builtins into functions and variables, where the latter use two hooks now: One when compiled and one when accessed. Previously, variables were handled explicitly, whereas now these can be registered. The change also uncovered an issue with the `memory.atomic.waitXY` instructions that weren't correctly registering, which now is fixed.
> Check that builtins are implemented

- src/compiler.ts
- tests/compiler/constructor.debug.wat
- tests/compiler/constructor.release.wat
- tests/compiler/constructor.ts
When use parent constructor as child default constructor, function signature should update `thisType` and `returnType` instead of directly using parent constructor
> fix: update this and return type in child class constructor #2574

- src/module.ts
Adds the respective constants to eventually emit relaxed SIMD instructions. Turns out these still need Binaryen APIs.
> Add relaxed SIMD constants

- src/compiler.ts
- tests/compiler/instanceof.debug.wat
- tests/compiler/instanceof.release.wat
- tests/compiler/instanceof.ts
fix: #2660
switch the order of `compile pending instanceof helpers` and `set up override stubs`
> fix: `instanceof` in override function compile as unreachable

- src/bindings/js.ts
`performance.now()` and co. need to be called with the proper this value.
⯈ Ensure `performance.now()` is called properly.
⯈ Ensure `document.*` is called properly.
> Fix the bindings for performance.now() and document.*

- src/bindings/js.ts
- src/bindings/tsd.ts
- src/compiler.ts
- tests/compiler/bindings/esm.debug.d.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.json
- tests/compiler/bindings/esm.release.d.ts
- tests/compiler/bindings/esm.release.js
Generated bindings previously didn't include the runtime interface when `--exportRuntime` was provided. This change includes the interface in both the generated .js and .d.ts files.
> Handle exportRuntime in generated bindings

- src/builtins.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
- tests/compiler/simd.debug.wat
- tests/compiler/simd.release.wat
- tests/compiler/simd.ts
Fixes #2696 where it was discovered that SIMD store lane instructions used `v128` as the return type, but should use `void`.
> Fix SIMD Store Lane signatures

- .github/workflows/test.yml
- cli/index.d.ts
- tests/compiler.js
- tests/compiler/bindings/esm.debug.wat
- tests/compiler/bindings/esm.release.wat
- tests/compiler/bindings/noExportRuntime.debug.js
- tests/compiler/bindings/noExportRuntime.release.js
- tests/compiler/bindings/raw.debug.wat
- tests/compiler/bindings/raw.release.wat
- tests/compiler/std/math.release.wat
- tests/compiler/tsconfig.json
- tests/tokenizer.js
⯈ Ensure all tests are run in CI, including those involving experimental features
⯈ Fix the tokenizer test, as useless as it may be
⯈ Ensure the release fixtures and bindings fixtures are checked
⯈ Fix the typings for the `writeFile` CLI option, since strings are passed in too
⯈ Make VS Code complain less about variables in tests being redeclared in other files
Closes #2723.
> Small fixes for tests and CI

- src/compiler.ts
- src/diagnostics.ts
- src/program.ts
A slightly simpler variant of #2688 using a `Map`, so debug info entries are automatically deduplicated.
fixes #2688, see also #2686
> Use unique debug info per concrete function

- src/resolver.ts
- src/types.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/raw.debug.js
- tests/compiler/bindings/raw.release.js
- tests/compiler/features/reference-types.debug.wat
- tests/compiler/field-reference-types.json
- tests/compiler/field-reference-types.ts
⯈ Fix stringified nullable reference types
⯈ Report upon usage of reference types in fieldd
> Error on usage of reference types in fields

- std/assembly/staticarray.ts
- tests/compiler/std/staticarray.debug.wat
- tests/compiler/std/staticarray.release.wat
- tests/compiler/std/staticarray.ts
> fix: `StaticArray#concat` link child to incorrect parent

- src/compiler.ts
- src/types.ts
- tests/compiler/class-member-function-as-parameter.json
- tests/compiler/class-member-function-as-parameter.ts
> fix #2727 Type checker does not detect a signature mismatch

- src/compiler.ts
- src/program.ts
- tests/compiler/closure.json
- tests/compiler/closure.ts
> fix: diagnose not implement when assign value to closure variable

- src/compiler.ts
- tests/compiler/issues/2737.json
- tests/compiler/issues/2737.ts
⯈ Fix the long-standing bug where the compiler cries when referencing a generic namespaced function.
⯈ Error when builtin functions in namespaces are referenced without being called.
> Ensure call-less references to builtin functions in namespaces error

- NOTICE
- std/assembly/index.d.ts
Fixes [#2646 ](https://github.com/AssemblyScript/assemblyscript/issues/2646)
> fix: Cannot find global type 'CallableFunction'

- .github/workflows/publish.yml
- .github/workflows/test.yml
since all of issue mentioned in `dcodeIO/setup-node-nvm` are resolved.
Now `actions/setup-node` is available.
> ci: build action-node to install nodejs

- .github/workflows/test.yml
- .gitignore
- dist/.gitignore
- dist/asc.d.ts
- dist/assemblyscript.d.ts
- dist/transform.cjs
- dist/transform.d.ts
- dist/transform.js
- package-lock.json
- package.json
- scripts/build-dts.js
- scripts/build-web.js
- scripts/build.js
- src/tsconfig.json
- tests/compiler.js
- tests/import/index.ts
- tests/parser.js
⯈ Skip fixture comparisons in tests if compiling them failed
⯈ Update esbuild
⯈ Clean up the DTS generator
⯈ Update glob
⯈ Marginally clean up the web build thingy
⯈ Add a coverage job to CI; maybe Codecov can be used on it in the future?
> General cleanup

- .github/workflows/publish.yml
⯈ Allow the main branch to be published manually via the Actions tab
> Allow manually triggered publishes

- src/diagnosticMessages.json
- src/program.ts
- tests/compiler/interface-with-initializer.json
- tests/compiler/interface-with-initializer.ts
> fix: add diagnose when initializing field in interface

- src/passes/shadowstack.ts
- tests/compiler/resolve-unary.debug.wat
- tests/compiler/resolve-unary.release.wat
match `tostack(tostack(expr))` pattern in shadowstack pass.
> fix: handle nest `tostack` in shadowstack pass

- NOTICE
- std/assembly/date.ts
- tests/compiler/std/date.debug.wat
- tests/compiler/std/date.release.wat
- tests/compiler/std/date.ts
- tests/compiler/std/math.release.wat
The logic used by `Date.fromString` and `Date.parse` has a few issues:
- Incorrect handling of fractional seconds having more than 3 decimal places.  For example, `"2000-01-01T00:00:00.123456789Z"` was being treated as having 123456789 milliseconds, making the result wildly too large. Such values should be truncated to 3 decimal places before being interpreted as milliseconds.
- Incorrect handling of fractional seconds having _less_ than 3 decimal places.  For example `"2000-01-01T00:00:00.1"` was treated as having 1 millisecond, though it should be one tenth of a second (or 100 milliseconds).
- Ignoring any UTC offset (such as `+05:30` or `-08:00`), which is required by ISO 8601, RFC 3339, and the ECMAScript standard date format.
This PR addresses all three issues, and updates the …
> fix: Improve date parsing (fractional seconds, UTC offsets)

- src/resolver.ts
- tests/compiler/getter-setter-errors.json
- tests/compiler/getter-setter-errors.ts
This will introduce some incompatible with TS. since TS is support this but report undefined error in runtime.
> fix: diagnose when accessing setter only property

- src/compiler.ts
- src/flow.ts
- src/program.ts
- src/resolver.ts
- tests/compiler/typealias-errors.json
- tests/compiler/typealias-errors.ts
- tests/compiler/typealias.debug.wat
- tests/compiler/typealias.release.wat
- tests/compiler/typealias.ts
use `Flow` to store scoped type alias and lookup it when resolve `NamedType`.
> feat: implement scoped type alias

- bin/asinit.js
Detection terminal background technically is possible, but I don't want to introduce deps to resolve UI/UX issue.
like `asc` did, this PR provides `--noColors` opinion in `asinit` to disable colorful output .
Fixes #2816.
> fix: asinit support --noColors opinion

- cli/index.d.ts
- cli/index.js
- scripts/build-dts.js
Fixes #2829
⯈ Exposes the binaryen instance used by transforms as `Transform#binaryen`
⯈ Fixes the `.d.ts` type for `Transform#afterCompile`
> Binaryen on transform

- tests/compiler.js
The major difference is from +/-nan
```diff
diff --git a/tests/compiler/std/math.release.wat b/tests/compiler/std/math.release.wat
index 9e691da3..bc8b2785 100644
--- a/tests/compiler/std/math.release.wat
+++ b/tests/compiler/std/math.release.wat
@@ -49901,7 +49901,7 @@
call $~lib/builtins/abort
unreachable
end
-  f64.const -nan:0x8000000000000
+  f64.const nan:0x8000000000000
f64.const nan:0x8000000000000
f64.const 0
call $std/math/check<f64>
@@ -49945,7 +49945,7 @@
call $~lib/builtins/abort
unreachable
end
-  f64.const -nan:0x8000000000000
+  f64.const nan:0x8000000000000
f64.const nan:0x8000000000000
f64.const 0
call $std/math/check<f64>
@@ -49967,7 +49967,7 @@
call $~lib/builtins/abort
unreachable
end
-  f64.const -nan:0x8000000000000
+  f64.const nan:0x8000000000000
f64.const …
```
> chore: temporary disable std/math.release.wat check in aarch64 osx

- src/bindings/js.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/noExportRuntime.debug.js
- tests/compiler/bindings/noExportRuntime.release.js
Use a better way to identifier exection environemt becasue `try` and `catch` will cause misleaded error message
> fix: use `typeof self === object && self.constructor` to identifier execution environment

- std/portable/index.js
Whenever importing from within a transform,
```js
import { Transform } from "assemblyscript/dist/transform.js";
import { Parser } from "assemblyscript/dist/assemblyscript.js";
```
I get the following warning:
`compiler mismatch: std/portable included twice`
The warning occurs with nearly every transform I have written and since it writes to `stderr` which is problematic.
Instead of warning the user when `std/portable` is imported twice, it seems more reasonable just to ignore it altogether. After all, its the compiler importing it twice, not the user.
> fix: std/portable included twice

- NOTICE
- package-lock.json
- package.json
- src/builtins.ts
- src/tokenizer.ts
- tests/compiler/std/string-encoding.ts
- tests/compiler/std/string.ts
⯈ Upgrade TypeScript to 5.5.4 from 4.7.4
Notice: eslint emits a warning about the typescript version and checks pass however attempting to upgrade eslint seems to be more involved.
> chore: typescript: 4.7.4 → 5.5.4

- src/parser.ts
- tests/parser/union.ts
- tests/parser/union.ts.fixture.ts
> fix: report error for mulitple union type

- lib/rtrace/tlsfvis.html
`<li>` cannot be included in `<p>`
see https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
> chore: fix `tlsfvis.html` label issue

- cli/index.js
remove redundant word in comment
⯈
⯈
⯈
> chore: remove redundant word in comment

- .github/workflows/test.yml
It looks like we missed this when removing every other instance of setup-node-nvm in #2779.
> chore: remove last instance of setup-node-nvm

- NOTICE
- std/assembly/index.d.ts
Fixes #2877 
⯈ Changes made in the TypeScript declaration file `std/assembly/index.d.ts`, where the v128.extract_lane functions are declared.
⯈ Comments now include: `idx argument needs to be compile time constant.` 
⯈
- [ x] I've read the contributing guidelines
- [ x] I've added my name and email to the NOTICE file
> chore: enhance comment for extract_lane functions to include "idx" argument needs to be compile time constant

- src/resolver.ts
- tests/compiler/call-inferred.debug.wat
- tests/compiler/call-inferred.release.wat
- tests/compiler/call-inferred.ts
Fixes #2893.
Enables type inference for constructors of generic classes by:
- Refactoring to extract the existing type inference logic for functions that was in `maybeInferCall`, into its own private method `inferGenericTypeArguments`.
- Calling that new method from `resolveClassInclTypeArguments` when a generic class's constructor is called without any type arguments.
- Expanding the unit tests to verify working functionality and no regressions.
> feat: Constructor generic type inference

- .github/workflows/publish.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- package-lock.json
- package.json
- Update minimum Node and NPM versions (Node 16 is EOL)
- Update all dependencies to latest version that build and pass tests without significant code changes
- `npm audit fix` for two ReDoS patches (lockfile only, on `cross-spawn` and `micromatch`)
- Fixed one minor warning about the order of `types` in `package.json`, which was seen after updating `esbuild` to latest
- Updated GitHub Actions to latest versions
- Removed code that was installing npm v6 because the linked bug was fixed some time ago.
I reviewed the change logs for these packages, and I think they should be ok.
I was not able to update `binaryen` without build/test failures.  I'll look into this separately if I can find some time.
I know how to update `eslint` and `typescript-eslint` …
> chore: update dependencies

- src/builtins.ts
- src/compiler.ts
- src/flow.ts
- std/assembly/builtins.ts
- std/assembly/index.d.ts
- tests/compiler/inlining.debug.wat
- tests/compiler/inlining.release.wat
- tests/compiler/inlining.ts
⯈ Add an `alwaysInline` builtin that inlines any inner function calls
> feat: add an alwaysInline builtin

- std/assembly/index.d.ts
⯈ Replace an erroneous `declare` with `export`
> fix: remove erroneous `declare` for `inline.always`

- .github/workflows/pr.yml
- package-lock.json
- package.json
This is necessary for #2920 due to AssemblyScript/as-float#1. Also, Node v18 is end-of-life.
This PR should be merged along with #2920 so both are present in the same release window.
> breaking: bump supported Node.js version to v20+

- src/bindings/js.ts
- tests/compiler/bindings/esm.debug.js
- tests/compiler/bindings/esm.release.js
- tests/compiler/bindings/noExportRuntime.debug.js
- tests/compiler/bindings/noExportRuntime.release.js
- tests/compiler/bindings/raw.debug.js
- tests/compiler/bindings/raw.release.js
Fixes #2659.
⯈ Use `Object.setPrototypeOf({ /* instrumented imports */ }, __moduleN)` instead of `Object.assign(Object.create(__moduleN), { /* instrumented imports */ })`
> fix: use Object.setPrototypeOf in JS bindings

- src/compiler.ts
- tests/compiler/switch.debug.wat
- tests/compiler/switch.release.wat
- tests/compiler/switch.ts
Fixes #2919
Fixes #648
- Fixes compiler error when using a `switch` statement with certain types.
- All numeric types that were already supported
- Add support for strings, floats, and 64-bit ints
- Adds tests to validate
I've reused the existing equality comparison logic, so any behavior for `==` is retained for switch cases, including overloads, etc.
> feat: support more types in switch statements

- bin/asinit.js
Fixes AssemblyScript/website#237. When the "type" field isn't specified, or if package.json doesn't exist, it's already set to "module". This removes the remaining hole when "type" is set to, say, "commonjs", by refusing to continue.
> fix: make asinit exit if package.json has a "type" not equal to "module"

- src/compiler.ts
- tests/compiler/logical.debug.wat
- tests/compiler/logical.release.wat
- tests/compiler/logical.ts
- tests/compiler/resolve-binary.debug.wat
Fixes #2946.
⯈ Precompute the LHSes of `&&` and `||` when possible
⯈ Simplify the emitted expression for `&&` and `||` if LHS is a constant value
> fix: simplify && and || when the LHS is constant

- src/compiler.ts
- tests/compiler/std/operator-overloading.debug.wat
- tests/compiler/std/operator-overloading.release.wat
In original code, `getLocalSetValue` cannot get the original expression accurately. For managed objects, the original expression will be wrapped in a layer of `tostack`, and will be wrapped in another layer of `tostack` when called. Although the subsequent nested `tostack` can be eliminated, this brings some readability issues.
> chore: refactor unary postfix code emitter to reduce nested tostack
