.gitattributes
.travis.yml
scripts/check-pr.sh
src/types.ts

Just experimenting with adding a stage that runs for PRs only. Could then check if dist files are present, for example.

Add a build check for PRs

---

.travis.yml
src/compiler.ts
src/program.ts
tests/compiler/std/operator-overloading.optimized.wat
tests/compiler/std/operator-overloading.ts
tests/compiler/std/operator-overloading.untouched.wat

1. Add following operators overloading:
> * operator '-'
> * operator '*'
> * operator '/'
> * operator '%'
> * operator '&'
> * operator '|'
> * operator '^'
2. Add more covered test.

Add more operation overloading and more tests

---

std/assembly/string.ts
tests/compiler/std/array-access.optimized.wat
tests/compiler/std/array-access.untouched.wat
tests/compiler/std/string.optimized.wat
tests/compiler/std/string.untouched.wat

Fix this cases:
null >= null  // => true
null <= null  // => true

Fix some cases in string comparision

---

std/portable/memory.js

Remove type checking from load/store for portable

---

src/parser.ts
tests/parser/var.ts
tests/parser/var.ts.fixture.ts

Try to fix TS1005 unexpected error

---

std/assembly/array.ts
std/assembly/internal/array.ts
std/assembly/internal/typedarray.ts
tests/compiler/std/array-literal.optimized.wat
tests/compiler/std/array-literal.untouched.wat
tests/compiler/std/array.optimized.wat
tests/compiler/std/array.ts
tests/compiler/std/array.untouched.wat
tests/compiler/std/gc-array.optimized.wat
tests/compiler/std/gc-array.untouched.wat
tests/compiler/std/static-array.optimized.wat
tests/compiler/std/static-array.untouched.wat
tests/compiler/std/typedarray.optimized.wat
tests/compiler/std/typedarray.ts
tests/compiler/std/typedarray.untouched.wat

Squashed and rebased version of #181

Add <typedarray>#sort method and improve default comparator for different types

---

NOTICE
std/assembly/index.d.ts

Add `  get(key: K): V;` for std/map in assembly/index.d.ts

Add get declare method for std/map

---

std/assembly/math.ts
tests/compiler/binary.optimized.wat
tests/compiler/binary.untouched.wat
tests/compiler/std/math.optimized.wat
tests/compiler/std/math.untouched.wat
tests/compiler/std/mod.optimized.wat
tests/compiler/std/mod.untouched.wat

In my tests this take 2-4% speedup for Math.mod
+ also reduce size a bit

Improve per-bit divmod loop for mod & rem

---

CONTRIBUTING.md
NOTICE
README.md
lib/lint/README.md

Update linting instructions to reference new script name

---

std/assembly/internal/typedarray.ts
std/assembly/typedarray.ts
tests/compiler/std/typedarray.optimized.wat
tests/compiler/std/typedarray.ts
tests/compiler/std/typedarray.untouched.wat

fix byteLength and subarray

---

std/assembly/index.d.ts
tests/compiler/std/operator-overloading.ts

This changes allow autocomplete and verify only supported set of tokens

Improve operator declarations.

---

src/compiler.ts

see: https://github.com/MaxGraey/bignum.wasm/issues/14
@MaxGraey Can you confirm that this fixes the problem?

Fix declaration mismatch in generated constructors

---

src/ast.ts
src/builtins.ts
src/compiler.ts
std/assembly/builtins.ts
std/assembly/index.d.ts
tests/compiler.js
tests/compiler/threads.json
tests/compiler/threads.optimized.wat
tests/compiler/threads.ts
tests/compiler/threads.untouched.wat
tests/features.json

fixes https://github.com/AssemblyScript/assemblyscript/issues/523

Add atomic definitions

---

.travis.yml
README.md
examples/game-of-life/index.html
examples/mandelbrot/index.html
examples/n-body/index.html
package-lock.json
package.json
src/builtins.ts
src/module.ts
std/assembly/builtins.ts
std/assembly/index.d.ts
tests/compiler/builtins.optimized.wat
tests/compiler/builtins.ts
tests/compiler/builtins.untouched.wat
tests/compiler/threads.ts

This branch consolidates some general clean up that makes sense to do after a variety of other PRs have landed.

General cleanup

---

std/assembly/index.d.ts
std/assembly/internal/typedarray.ts
std/assembly/typedarray.ts
tests/compiler/std/typedarray.optimized.wat
tests/compiler/std/typedarray.ts
tests/compiler/std/typedarray.untouched.wat

This should be all set for review.

TypedArray#reverse

---

src/module.ts
tests/compiler/function.ts
tests/compiler/function.untouched.wat

Close https://github.com/AssemblyScript/assemblyscript/issues/556

fix unreachable for None return types

---

lib/rtrace/index.d.ts
lib/rtrace/package.json
package.json

Include `rtrace` with the `assemblyscript` package.
All feedback is welcome.

Add RTrace support and Types

---

std/assembly/index.d.ts
std/portable/index.d.ts

Fix String declarations

---

README.md

As discussed in the slack at some point :smile: 
Also, just FYI this happened as well: https://www.programmableweb.com/news/google-recommends-assemblyscript-web-assembly-programming/2019/05/08 :+1:

Added some quotes from Google I/O 2019 to the README

---

src/compiler.ts

fixes https://github.com/AssemblyScript/assemblyscript/issues/755

Retain reftype parameter field initializers in ctors

---

tests/compiler/std/math.optimized.wat
tests/compiler/std/math.ts
tests/compiler/std/math.untouched.wat

`Math.mod` or `af % bf` operator is pretty important so I think it should have better code coverage

Add Math.mod tests with subnormals & special cases

---

src/flow.ts
tests/compiler/continue.json
tests/compiler/continue.optimized.wat
tests/compiler/continue.ts
tests/compiler/continue.untouched.wat

fixes https://github.com/AssemblyScript/assemblyscript/issues/813

Properly propagate existing conditionals in flows

---

src/parser.ts

fixes https://github.com/AssemblyScript/assemblyscript/issues/878

Fix return statement range

---

lib/loader/index.d.ts

Fix loader definisions

---

src/compiler.ts
src/resolver.ts

The resolver wasn't yet capable of inferring calls in subexpressions of inferred expressions, so this PR fixes that by sharing the respective logic, that only the compiler had, between the resolver and the compiler.

Share call infer logic between resolver and compiler

---

std/assembly/bindings/asyncify.ts

Have been toying around with asyncify a bit, but without concrete results yet. For now, this simply adds Wasm-side bindings fwiw.

Add asyncify bindings

---

cli/asc.js

As reported in https://github.com/AssemblyScript/assemblyscript/issues/996 there is something wrong with source maps currently. The issue reported there seems to be caused by using the wrong key inside of the JSON-like `.map` file for source contents, namely `sourceContents` instead of the correct `sourcesContent`.
This PR renames the key to the proper one, but I actually have no idea how this did work in the past, which it definitely did when I last tested. Makes me wonder if browsers used to also accept `sourceContents` up to some point, and removed that.
Another issue I had locally was that, when just `--sourceMap` was used without an absolute path, we are setting the `sourceMappingURL` section to `thefile.wasm.map`, assuming that the browser will load this relative to `thefile.wasm`, …

Fix source contents in source maps

---

std/assembly/index.d.ts

Remove call_indirect & call_direct from definitions

---

examples/sdk/README.md
examples/sdk/index.html
lib/sdk/README.md
lib/sdk/index.js
lib/sdk/tests/index.html
scripts/build-sdk.js

This adds an example of using the browser SDK. Now the SDK isn't very sophisticated yet, but it works, so why not let everyone play with it.

Add a browser SDK example

---

README.md
std/assembly/rt.ts

- Fix CI badge which now reflect only CI workflow of master with "push" event.
- remove unnecessary type change inside __allocArray

Minor improvments

---

lib/loader/index.d.ts

fix Import definition for loader

---

cli/util/options.d.ts

While we are here, should we check the d.ts files are correct? Are there any other options for generating these dts files because they tend to get outdated, and are subject to developer error very often.

update options definition

---

lib/loader/index.d.ts

I made the changes locally to my d.ts file and verified that the result is stable. Here's the output of the new Imports type.
Anything need to be changed or made clearer?

Fix env imports problem

---

cli/util/options.d.ts

add category to d.ts file

---

.github/workflows/publish.yml
package-lock.json
package.json

The relevant bugs have been tackled now, so this is a good time to slice 0.10.1.
Also disables publishing to GPR, since that's not working anyway due to our dependencies not being available there. Going to remove the existing package on GPR as well then.

Slice version 0.10.1

---

README.md
lib/loader/README.md

Removes the nightly badge from the loader package. Updates some other badges as well.

chore: Update badges

---

src/parser.ts
tests/parser/interface.ts
tests/parser/interface.ts.fixture.ts

Fix parsing comma separator for interfaces

---

cli/shim/process.js
webpack.config.js

- use parallel mode for Terser
- improve hrtime shim code

build and shim improvments

---

bin/asinit

Fix asinit keeping npm default test

---

src/compiler.ts
tests/compiler/unify-local-flags.json
tests/compiler/unify-local-flags.optimized.wat
tests/compiler/unify-local-flags.ts
tests/compiler/unify-local-flags.untouched.wat

fixes https://github.com/AssemblyScript/assemblyscript/issues/1483

Keep recompiling when unifying local flags (locals may depend on each other)

---

README.md

Add link to examples in readme.md

---

package-lock.json
package.json
src/module.ts
tests/compiler/extends-baseaggregate.optimized.wat
tests/compiler/memmove.optimized.wat
tests/compiler/retain-release-sanity.optimized.wat
tests/compiler/retain-return.optimized.wat
tests/compiler/std/array-literal.optimized.wat
tests/compiler/std/math.optimized.wat
tests/compiler/std/mod.optimized.wat
tests/compiler/std/string.optimized.wat
tests/compiler/std/typedarray.optimized.wat

After https://github.com/WebAssembly/binaryen/pull/3274 we need slightly refactor our pass pipeline

Update binaryen. Slightly improve pass pipeline

---

bin/asinit

This will be easier for tuning optimization for speed or for size.

Use more detailed release config for asconfig template

---

src/compiler.ts

Now always goes through `Compiler#ensureArgumentsLength` before use.
fixes https://github.com/AssemblyScript/assemblyscript/issues/1673

Make sure the ~argumentsLength global exists

---

tests/README.md

Update tests README for feature flags

---

tests/compiler/std/typedarray.optimized.wat
tests/compiler/std/typedarray.ts
tests/compiler/std/typedarray.untouched.wat

Adds missing tests for `TypedArray#sort`

tests: Add tests for TypedArray#sort

---

src/definitions.ts

Fixed missing getter property definitions.

---

NOTICE
src/glue/js/float.js

I've read the contributing guidelines

fix: typo correction

---

.github/workflows/test.yml

Fix CI for features

---

std/assembly/array.ts
std/assembly/index.d.ts
tests/compiler/std/array.optimized.wat
tests/compiler/std/array.untouched.wat

fix: expose dataStart to definitions

---

std/assembly/date.ts
std/assembly/index.d.ts
tests/compiler/std/date.optimized.wat
tests/compiler/std/date.ts
tests/compiler/std/date.untouched.wat

Add toUTCString for Date

---

.github/workflows/stale.yml

Docs: https://github.com/actions/stale#readme

Stale bot is dead, long live stale action

---

src/resolver.ts

Fix assertion on invalid generic operator overloads

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test.yml

chore(ci): Remove checking author in PRs

---

cli/asc.js

chore: minor reafactoring for asc.js

---

.github/workflows/test.yml

Pin node vertion to 17.0.0-v8-canary202108069771f4a956 for features test

---

cli/asc.js

feat: do checkDiagnostics after `afterCompile`

---

std/assembly/polyfills.ts
tests/compiler/std/array.untouched.wat
tests/compiler/std/dataview.untouched.wat
tests/compiler/std/polyfills.untouched.wat
tests/compiler/std/typedarray.untouched.wat

[std] Improve bswap

---

package-lock.json
package.json

Accidental this was changed in #2057

change typescript deps prefix

---

src/module.ts

Expose try for exception handling

---

package-lock.json
package.json

Update typescript to 4.5 + other deps

---

package-lock.json
package.json
src/glue/js/i64.d.ts
src/glue/js/i64.js
src/glue/wasm/i64.ts

We will need these operations in the near future

Add clz and ctz unary operations for glue/i64

---

tests/compiler/duplicate-fields.optimized.wat

Update duplicate-fields fixture after #2158

---

std/portable/index.js

Refactor `TypedArray.wrap` polyfills

Simplify wrap polyfill in portable

---

src/diagnosticMessages.json
src/program.ts

Emit a diagnostic when a --use element cannot be found

---

src/module.ts

Defuse assert when flattening after already diagnosing an error

---

NOTICE
tests/compiler/builtins.debug.wat
tests/compiler/builtins.release.wat
tests/compiler/builtins.ts

chore: add add/sub/mul/div instructions to tests/buildins

---

cli/index.js

fix: typo suboptimial to suboptimal (#2332)

---

std/assembly/index.d.ts

fix: fix type of slice

---

src/parser.ts

fix with issue [2372](https://github.com/AssemblyScript/assemblyscript/issues/2372)
fix the incurrrect error message issue

fix: incorrect error message for declaration

---

package-lock.json
package.json

Latest esbuild has some security fixes. Also add support names attr for source maps

Update esbuild & typescript dependencies

---

tests/compiler/simd.debug.wat
tests/compiler/simd.release.wat
tests/compiler/simd.ts

Fix: [2374](https://github.com/AssemblyScript/assemblyscript/issues/2374)
add the missing test cases for v128.

Add missing unit tests for simd

---

src/bindings/js.ts

[bindings] add size types for path path lowering in StaticArray

---

scripts/build.js
std/portable.json
tsconfig-base.json

Disable "preserveConstEnums" in tsconfig

---

cli/index.js

fix: properly check undefined exportStart option

---

src/module.ts

Also kind of a TODO list for instructions the Binaryen bindings don't yet support. Needing these for an IR experiment, so adding already.

Add various Binaryen constant for new instructions

---

std/assembly/math.ts
tests/compiler/std/math.debug.wat

Add optimized path of Math.round for prefered size mode

---

.github/workflows/test.yml

[CI] update v8-canary version

---

std/assembly/process.ts

These are only available with the WASI shim.

Fix: Remove leftover process streams

---

src/program.ts

A fix discovered in #2510 that makes sense to merge immediately.

Fix internal setter signature caching

---

src/glue/binaryen.d.ts
src/glue/binaryen.js

Add remaining heap type APIs

---

.github/workflows/test.yml

This change depends on dcodeIO/setup-node-nvm#14.
⯈
⯈
⯈

Re-add Windows to CI

---

src/parser.ts
src/tokenizer.ts
tests/parser/asi.ts
tests/parser/asi.ts.fixture.ts

Fixes AssemblyScript/website#188

fix: Maintain onNewLine state on subsequent lookahead

---

src/module.ts

Add reorder-globals pass to pass pipeline

---

std/assembly/process.ts

fix: Fix missing cast in process.ts

---

src/resolver.ts
tests/compiler/class-implements.debug.wat
tests/compiler/class-implements.release.wat
tests/compiler/class-implements.ts

fix: interface inheritance cause crash

---

.github/workflows/stale.yml

There are lots of unmaintained PR in this project.
This patch want to let stable action close those inactive PR automatically.

ci: close inactive pull request
